# Generated by Django 5.2.1 on 2026-04-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ENGENHARIA', 'Engenharia'), ('ORCAMENTISTA', 'Orçamentista'), ('ALMOXARIFADO', 'Almoxarifado'), ('USUARIO', 'Colaborador (geral)')], default='USUARIO', max_length=20, verbose_name='tipo de usuário'),
        ),
    ]
