# Generated by Django 5.2.1 on 2026-05-25 00:18

import core.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_produto_aliquota_ipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, help_text='Classificação livre (ex.: Montagem, Engenharia).', max_length=120)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('MT', 'Metro'), ('CJ', 'Conjunto'), ('KM', 'Kilometro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cubico'), ('KG', 'Kilograma'), ('G', 'Gramas'), ('L', 'Litro'), ('HORAS', 'Horas')], default='HORAS', max_length=10)),
                ('preco_base', models.DecimalField(decimal_places=2, default=0, help_text='Preço/custo de referência para propostas.', max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Serviço do catálogo',
                'verbose_name_plural': 'Serviços do catálogo',
                'db_table': 'catalogo_servico',
                'ordering': ('codigo', 'descricao'),
            },
            bases=(core.models.mixins.UpperCaseMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='especificacaoborne',
            name='tipo_borne',
            field=models.CharField(choices=[('PASSAGEM', 'Passagem'), ('TERRA', 'Terra'), ('FUSIVEL', 'Fusível'), ('SECCIONAVEL', 'Seccionável'), ('SENSOR', 'Sensor'), ('AFERICAO', 'Borne de aferição'), ('TAMPA', 'Tampa'), ('JUMPER', 'Jumper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada'), ('MINIDISJUNTOR', 'Minidisjuntor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('SECCIONADORA', 'Seccionadora'), ('FUSIVEL', 'Fusível'), ('RELE_ESTADO_SOLIDO', 'Relé Estado Sólido'), ('INVERSOR_FREQUENCIA', 'Inversor de Frequência'), ('SOFT_STARTER', 'Soft Starter'), ('BOTAO', 'Botão de Comando'), ('CHAVE_SELETORA', 'Chave Seletora'), ('SINALIZADOR', 'Sinaleiro'), ('RELE_INTERFACE', 'Relé de Interface'), ('TEMPORIZADOR', 'Relé Temporizador'), ('CONTROLADOR_TEMPERATURA', 'Controlador de Temperatura'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('IHM', 'Interface Homem Máquina (IHM)'), ('MODULO_COMUNICACAO', 'Módulo de Comunicação'), ('GATEWAY', 'Gateway'), ('SWITCH_REDE', 'Switch Industrial'), ('RELE_SEGURANCA', 'Relé de Segurança'), ('FONTE_CHAVEADA', 'Fonte Chaveada'), ('BORNE', 'Borne'), ('BARRAMENTO', 'Barramento'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('TRILHO_DIN', 'Trilho DIN'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros'), ('SEM_REGRA_SUGESTAO_AUTOMATICA', 'Sem regra de sugestão automática')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('MT', 'Metro'), ('CJ', 'Conjunto'), ('KM', 'Kilometro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cubico'), ('KG', 'Kilograma'), ('G', 'Gramas'), ('L', 'Litro'), ('HORAS', 'Horas')], default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_tributavel',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('MT', 'Metro'), ('CJ', 'Conjunto'), ('KM', 'Kilometro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cubico'), ('KG', 'Kilograma'), ('G', 'Gramas'), ('L', 'Litro'), ('HORAS', 'Horas')], help_text='Se vazio, usar a unidade comercial do produto (uCom).', max_length=10, verbose_name='Unidade tributável (uTrib)'),
        ),
    ]
