# Generated by Django 5.2.1 on 2026-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_rename_canaleta_largura_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacaoborne',
            name='tipo_borne',
            field=models.CharField(choices=[('PASSAGEM', 'Passagem'), ('TERRA', 'Terra'), ('FUSIVEL', 'Fusível'), ('SECCIONAVEL', 'Seccionável'), ('SENSOR', 'Sensor'), ('AFERICAO', 'Borne de aferição'), ('TAMPA', 'Tampa'), ('POSTE', 'Poste'), ('JUMPER', 'Jumper')], max_length=20),
        ),
    ]
