# Generated by Codex on 2026-06-07

import decimal
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0010_add_tipo_borne_poste"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutoAcessorioCompativel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_acessorio",
                    models.CharField(
                        choices=[
                            ("PASSAGEM", "Passagem"),
                            ("TERRA", "Terra"),
                            ("FUSIVEL", "Fusível"),
                            ("SECCIONAVEL", "Seccionável"),
                            ("SENSOR", "Sensor"),
                            ("AFERICAO", "Borne de aferição"),
                            ("TAMPA", "Tampa"),
                            ("POSTE", "Poste"),
                            ("JUMPER", "Jumper"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantidade_padrao",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("1"),
                        max_digits=10,
                    ),
                ),
                ("prioridade", models.PositiveSmallIntegerField(default=0)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "acessorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos_base_compativeis",
                        to="catalogo.produto",
                    ),
                ),
                (
                    "produto_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessorios_compativeis",
                        to="catalogo.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acessório compatível",
                "verbose_name_plural": "Acessórios compatíveis",
                "ordering": [
                    "produto_base__codigo",
                    "tipo_acessorio",
                    "prioridade",
                    "acessorio__codigo",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="produtoacessoriocompativel",
            constraint=models.UniqueConstraint(
                fields=("produto_base", "acessorio", "tipo_acessorio"),
                name="uq_produto_acessorio_compativel",
            ),
        ),
    ]
