# Generated by Codex on 2026-06-07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0011_produto_acessorio_compativel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecificacaoTerminal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_terminal",
                    models.CharField(
                        choices=[
                            ("TUBULAR", "Tubular"),
                            ("OLHAL_PRE_ISOLADO", "Olhal pré-isolado"),
                            ("OLHAL_NAO_ISOLADO", "Olhal não isolado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "secao_min_mm2",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "secao_max_mm2",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "furo_olhal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M4", "M4"),
                            ("M5", "M5"),
                            ("M6", "M6"),
                            ("M8", "M8"),
                            ("M10", "M10"),
                            ("M12", "M12"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especificacao_terminal",
                        to="catalogo.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especificação de Terminal",
                "verbose_name_plural": "Especificações de Terminais",
            },
        ),
    ]
