# Generated by Codex on 2026-06-07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0012_especificacao_terminal"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecificacaoIdentificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_identificacao",
                    models.CharField(
                        choices=[
                            ("SUPORTE_LUVA_CABO", "Suporte/luva para cabo"),
                            ("ETIQUETA_CABO", "Etiqueta de identificação de cabo"),
                            ("ADESIVO_ALERTA", "Adesivo de alerta"),
                            ("ADESIVO_TENSAO", "Adesivo de tensão"),
                            ("FAIXA_IDENTIFICACAO", "Faixa de identificação"),
                            ("PLAQUETA_IDENTIFICACAO", "Plaqueta de identificação"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "secao_min_mm2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "secao_max_mm2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "diametro_min_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "diametro_max_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "comprimento_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "tamanho_plaqueta",
                    models.CharField(
                        blank=True,
                        choices=[("PEQUENA", "Pequena"), ("GRANDE", "Grande")],
                        max_length=10,
                    ),
                ),
                ("tensao_v", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especificacao_identificacao",
                        to="catalogo.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especificação de Identificação",
                "verbose_name_plural": "Especificações de Identificação",
            },
        ),
    ]
