"""
Django settings do projeto (pacote `config`).

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") #, "unsafe-key"

# SECURITY WARNING: don't run with debug turned on in production!
# DJANGO_DEBUG explícito (true/false) tem prioridade; se ausente, DEBUG só é True
# quando DJANGO_ENV for development | dev | local (padrão em docker-compose local).


def _parse_optional_bool(name: str):
    v = os.getenv(name)
    if v is None or not str(v).strip():
        return None
    s = str(v).strip().lower()
    if s in ("1", "true", "yes", "on"):
        return True
    if s in ("0", "false", "no", "off"):
        return False
    return None


def _debug_from_environment() -> bool:
    explicit = _parse_optional_bool("DJANGO_DEBUG")
    if explicit is not None:
        return explicit
    env = os.getenv("DJANGO_ENV", "").strip().lower()
    return env in ("development", "dev", "local")


DEBUG = _debug_from_environment()

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://api.zfw.com.br",
    "https://portal.zfw.com.br",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://portal.zfw.com.br",
]

# Application definition

INSTALLED_APPS = [
    'django_prometheus',
    # auth + accounts antes de admin (AUTH_USER_MODEL): evita ordem confusa em projetos novos
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'apps.accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'core',
    'apps.catalogo.apps.CatalogoConfig',
    'apps.configurador_paineis.projetos.apps.ProjetosConfig',
    'apps.configurador_paineis.cargas.apps.CargasConfig',
    'apps.configurador_paineis.dimensionamento.apps.DimensionamentoConfig',
    'apps.configurador_paineis.selecao_componentes.apps.SelecaoComponentesConfig',
    'apps.configurador_paineis.composicao_painel.apps.ComposicaoPainelConfig',
    'apps.configurador_paineis.wizard.apps.WizardConfig',
    'apps.tarefas.apps.TarefasConfig',
    'apps.documentos.apps.DocumentosConfig',
    'apps.cadastros.apps.CadastrosConfig',
    'apps.orcamentos.apps.OrcamentosConfig',
    'apps.configuracoes_erp.apps.ConfiguracoesErpConfig',
    'apps.auditoria.apps.AuditoriaConfig',
    'apps.compras.apps.ComprasConfig',
    'apps.conformidade.apps.ConformidadeConfig',
    'apps.crm.apps.CrmConfig',
    'apps.estoque.apps.EstoqueConfig',
    'apps.expedicao.apps.ExpedicaoConfig',
    'apps.financeiro.apps.FinanceiroConfig',
    'apps.fiscal.apps.FiscalConfig',
    'apps.integracoes.apps.IntegracoesConfig',
    'apps.notificacoes.apps.NotificacoesConfig',
    'apps.pedidos_venda.apps.PedidosVendaConfig',
    'apps.pos_venda.apps.PosVendaConfig',
    'apps.producao.apps.ProducaoConfig',
    'apps.qualidade.apps.QualidadeConfig',
    'apps.relatorios.apps.RelatoriosConfig',
    'apps.rh.apps.RhConfig',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "accounts.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
