sonar.projectKey=zilioalberto_Configurador_Paineis_Eletricos
sonar.organization=zilioalberto
sonar.projectName=Configurador_Paineis_Eletricos
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,**/migrations/**,**/.venv/**,**/venv/**,**/build/**
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12