# Generated by Django 5.2.1 on 2026-05-09 17:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoHora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fim', models.DateTimeField(blank=True, null=True)),
                ('etapa', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('GESTOR', 'Gestor'), ('SISTEMA', 'Sistema')], default='COLABORADOR', max_length=20)),
                ('status_aprovacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('AJUSTADO', 'Ajustado'), ('CANCELADO', 'Cancelado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20)),
                ('valor_hora_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('justificativa_ajuste', models.TextField(blank=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_horas_aprovados', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apontamento de hora',
                'verbose_name_plural': 'Apontamentos de horas',
                'ordering': ('-data', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='QuadroTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('equipe', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros_tarefa_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quadro de tarefa',
                'verbose_name_plural': 'Quadros de tarefas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='ColunaTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('status_semantico', models.CharField(choices=[('PENDENTE', 'Pendente'), ('INICIADA', 'Iniciada'), ('FINALIZADA', 'Finalizada'), ('EM_ANDAMENTO', 'Em andamento'), ('BLOQUEADO', 'Bloqueado'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('limite_wip', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='tarefas.quadrotarefa')),
            ],
            options={
                'verbose_name': 'Coluna de tarefa',
                'verbose_name_plural': 'Colunas de tarefas',
                'ordering': ('quadro__nome', 'ordem', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('INICIADA', 'Iniciada'), ('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('BLOQUEADA', 'Bloqueada'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('tipo_etapa', models.CharField(choices=[('NAO_CLASSIFICADA', 'Nao classificada'), ('PROPOSTA', 'Proposta'), ('PRODUCAO', 'Producao'), ('INTERNA', 'Interna')], default='NAO_CLASSIFICADA', max_length=20)),
                ('orcamento_referencia', models.CharField(blank=True, max_length=100)),
                ('ordem_producao_referencia', models.CharField(blank=True, max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='tarefas_colaborador', to=settings.AUTH_USER_MODEL)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='tarefas.colunatarefa')),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_supervisionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ('coluna__quadro__nome', 'coluna__ordem', 'ordem', 'prazo', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='SessaoTrabalhoTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('etapa', models.CharField(blank=True, default='Cronometro', max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('GESTOR', 'Gestor'), ('SISTEMA', 'Sistema')], default='COLABORADOR', max_length=20)),
                ('motivo_encerramento', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('FIM_JORNADA', 'Fim da jornada'), ('INICIO_INTERVALO', 'Inicio de intervalo'), ('AJUSTE_GESTOR', 'Ajuste do gestor'), ('SISTEMA', 'Sistema')], max_length=30)),
                ('apontamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessao_trabalho', to='tarefas.apontamentohora')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_trabalho_tarefas', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_trabalho', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Sessao de trabalho em tarefa',
                'verbose_name_plural': 'Sessoes de trabalho em tarefas',
                'ordering': ('-iniciado_em',),
            },
        ),
        migrations.CreateModel(
            name='HistoricoTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CRIADA', 'Criada'), ('EDITADA', 'Editada'), ('MOVIDA', 'Movida'), ('RESPONSAVEL', 'Responsavel alterado'), ('PRAZO', 'Prazo alterado'), ('CLASSIFICADA', 'Classificada'), ('INICIADA', 'Iniciada'), ('CONCLUIDA', 'Concluida'), ('APONTAMENTO', 'Apontamento de horas')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('prazo_anterior', models.DateTimeField(blank=True, null=True)),
                ('prazo_novo', models.DateTimeField(blank=True, null=True)),
                ('coluna_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_destino', to='tarefas.colunatarefa')),
                ('coluna_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_origem', to='tarefas.colunatarefa')),
                ('responsavel_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_responsavel_anterior', to=settings.AUTH_USER_MODEL)),
                ('responsavel_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_responsavel_novo', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Historico de tarefa',
                'verbose_name_plural': 'Historicos de tarefas',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Comentario de tarefa',
                'verbose_name_plural': 'Comentarios de tarefas',
                'ordering': ('criado_em',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_tarefa_concluidos', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Checklist de tarefa',
                'verbose_name_plural': 'Checklists de tarefas',
                'ordering': ('tarefa', 'ordem', 'titulo'),
            },
        ),
        migrations.AddField(
            model_name='apontamentohora',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='tarefas.tarefa'),
        ),
        migrations.AddConstraint(
            model_name='colunatarefa',
            constraint=models.UniqueConstraint(fields=('quadro', 'ordem'), name='tarefas_coluna_quadro_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='colunatarefa',
            constraint=models.UniqueConstraint(fields=('quadro', 'nome'), name='tarefas_coluna_quadro_nome_unico'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['status', 'prazo'], name='tarefas_status_prazo_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['responsavel', 'status'], name='tarefas_resp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaotrabalhotarefa',
            index=models.Index(fields=['tarefa', '-iniciado_em'], name='tarefas_sess_tarefa_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaotrabalhotarefa',
            index=models.Index(fields=['colaborador', 'finalizado_em'], name='tarefas_sess_colab_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessaotrabalhotarefa',
            constraint=models.UniqueConstraint(condition=models.Q(('finalizado_em__isnull', True)), fields=('colaborador',), name='tarefas_sess_ativa_colab_unq'),
        ),
    ]
