[pytest]
DJANGO_SETTINGS_MODULE = portal.settings_ci
python_files = test_*.py *_test.py tests.py
testpaths = portal/tests accounts/tests configurador/projetos/tests configurador/composicao_painel/tests configurador/cargas/tests catalogo/tests configurador/dimensionamento/tests core/tests
