[pytest]
DJANGO_SETTINGS_MODULE = configuracoes.settings_ci
python_files = test_*.py *_test.py tests.py
testpaths = configuracoes/tests accounts/tests projetos/tests composicao_painel/tests cargas/tests catalogo/tests
