# Generated by Django 5.2.1 on 2026-05-09 17:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tag', models.CharField(help_text='Ex.: M01, YV01, R01, ST01', max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('MOTOR', 'Motor'), ('VALVULA', 'Válvula'), ('RESISTENCIA', 'Resistência'), ('SENSOR', 'Sensor'), ('TRANSDUTOR', 'Transdutor'), ('TRANSMISSOR', 'Transmissor')], max_length=30)),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('local_instalacao', models.CharField(blank=True, help_text='Ex.: Campo, skid, painel, área externa', max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('exige_protecao', models.BooleanField(default=True)),
                ('exige_seccionamento', models.BooleanField(default=False)),
                ('exige_comando', models.BooleanField(default=False)),
                ('quantidade_entradas_digitais', models.PositiveIntegerField(default=0)),
                ('quantidade_entradas_analogicas', models.PositiveIntegerField(default=0)),
                ('quantidade_saidas_digitais', models.PositiveIntegerField(default=0)),
                ('quantidade_saidas_analogicas', models.PositiveIntegerField(default=0)),
                ('quantidade_entradas_rapidas', models.PositiveIntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['projeto', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='CargaModelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('MOTOR', 'Motor'), ('VALVULA', 'Válvula'), ('RESISTENCIA', 'Resistência'), ('SENSOR', 'Sensor'), ('TRANSDUTOR', 'Transdutor'), ('TRANSMISSOR', 'Transmissor')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_modelos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_modelos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de carga',
                'verbose_name_plural': 'Modelos de carga',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CargaMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_corrente_valor', models.DecimalField(decimal_places=2, help_text='Valor informado em CV, kW ou A.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('potencia_corrente_unidade', models.CharField(choices=[('CV', 'CV'), ('KW', 'kW'), ('A', 'Ampere')], default='CV', help_text='Unidade do valor informado.', max_length=5)),
                ('numero_fases', models.IntegerField(choices=[(1, 'Monofásico'), (2, 'Bifásico'), (3, 'Trifásico')], default=3, help_text='Número de fases do motor.')),
                ('tensao_motor', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], help_text='Tensão nominal do motor.')),
                ('rendimento_percentual', models.DecimalField(blank=True, decimal_places=2, default=Decimal('85.00'), help_text='Rendimento do motor em percentual. Ex.: 85.00', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fator_potencia', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.85'), help_text='Fator de potência em formato decimal. Ex.: 0.85', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo_partida', models.CharField(choices=[('DIRETA', 'Direta'), ('ESTRELA_TRIANGULO', 'Estrela-Triângulo'), ('SOFT_STARTER', 'Soft Starter'), ('INVERSOR', 'Inversor'), ('SERVO_DRIVE', 'Servo Drive')], default='DIRETA', max_length=30)),
                ('tipo_protecao', models.CharField(choices=[('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('FUSIVEL', 'Fusível'), ('FUSIVEL_ULTRARRAPIDO', 'Fusível Ultrarrápido'), ('MINIDISJUNTOR', 'Minidisjuntor')], default='DISJUNTOR_MOTOR', help_text='Tipo de proteção elétrica do motor.', max_length=30)),
                ('reversivel', models.BooleanField(default=False)),
                ('freio_motor', models.BooleanField(default=False)),
                ('tipo_conexao_painel', models.CharField(choices=[('CONEXAO_BORNES_COM_PE', 'Conexão a bornes com PE'), ('CONEXAO_BORNES_SEM_PE', 'Conexão a bornes sem PE'), ('CONEXAO_DIRETO_COMPONENTE', 'Conexão direta ao componente'), ('OUTROS', 'Outros')], default='CONEXAO_BORNES_COM_PE', help_text='Tipo de conexão da carga no painel.', max_length=50)),
                ('potencia_kw_calculada', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=10, null=True)),
                ('corrente_calculada_a', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'MOTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='motor', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Motor',
                'verbose_name_plural': 'Especificações de Motores',
            },
        ),
        migrations.CreateModel(
            name='CargaResistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fases', models.IntegerField(choices=[(1, 'Monofásico'), (2, 'Bifásico'), (3, 'Trifásico')], default=3, help_text='Número de fases da resistência.')),
                ('tensao_resistencia', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], help_text='Tensão nominal da resistência.')),
                ('tipo_protecao', models.CharField(choices=[('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('FUSIVEL_ULTRARRAPIDO', 'Fusível Ultrarrápido'), ('MINIDISJUNTOR', 'Minidisjuntor')], default='FUSIVEL_ULTRARRAPIDO', help_text='Tipo de proteção elétrica da resistência.', max_length=30)),
                ('tipo_acionamento', models.CharField(choices=[('CONTATOR', 'Contator'), ('RELE_ESTADO_SOLIDO', 'Relé de Estado Sólido'), ('RELE_INTERFACE', 'Relé de interface')], default='RELE_ESTADO_SOLIDO', help_text='Tipo de acionamento da resistência.', max_length=30)),
                ('tipo_rele_interface', models.CharField(blank=True, choices=[('ELETROMECANICA', 'Eletromecânica'), ('ESTADO_SOLIDO', 'Estado sólido')], help_text='Quando o acionamento é relé de interface: eletromecânico ou estado sólido.', max_length=30, null=True)),
                ('tipo_conexao_painel', models.CharField(choices=[('CONEXAO_BORNES_COM_PE', 'Conexão a bornes com PE'), ('CONEXAO_BORNES_SEM_PE', 'Conexão a bornes sem PE'), ('CONEXAO_DIRETO_COMPONENTE', 'Conexão direta ao componente'), ('OUTROS', 'Outros')], default='CONEXAO_BORNES_COM_PE', help_text='Tipo de conexão da carga no painel.', max_length=50)),
                ('potencia_kw', models.DecimalField(decimal_places=3, help_text='Potência da resistência em kW.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('corrente_calculada_a', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'RESISTENCIA'}, on_delete=django.db.models.deletion.CASCADE, related_name='resistencia', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Resistência',
                'verbose_name_plural': 'Especificações de Resistências',
            },
        ),
        migrations.CreateModel(
            name='CargaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sensor', models.CharField(choices=[('INDUTIVO', 'Indutivo'), ('CAPACITIVO', 'Capacitivo'), ('FOTOELETRICO', 'Fotoelétrico'), ('FIM_DE_CURSO', 'Fim de curso'), ('PRESSOSTATO', 'Pressostato'), ('TERMOSTATO', 'Termostato'), ('CHAVE_NIVEL', 'Chave de nível'), ('ENCODER', 'Encoder')], max_length=30)),
                ('tipo_sinal', models.CharField(choices=[('DIGITAL', 'Digital'), ('ANALOGICO', 'Analógico'), ('ANALOGICO_DIGITAL', 'Analógico/Digital'), ('PULSO', 'Pulso'), ('COMUNICACAO', 'Comunicação')], default='DIGITAL', max_length=30)),
                ('tipo_sinal_analogico', models.CharField(blank=True, choices=[('TENSAO_0_10VCC', 'Tensão 0-10 VCC'), ('TENSAO_M10_10VCC', 'Tensão -10 a 10 VCC'), ('CORRENTE_0_20MA', 'Corrente 0-20 mA'), ('CORRENTE_4_20MA', 'Corrente 4-20 mA'), ('TEMPERATURA_PT100', 'Temperatura PT100'), ('TEMPERATURA_RTD', 'Temperatura RTD'), ('OUTROS', 'Outros')], max_length=30, null=True)),
                ('tensao_alimentacao', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=24, help_text='Tensão de alimentação do sensor.')),
                ('tipo_corrente', models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CC', help_text='Tipo de corrente da alimentação do sensor.', max_length=2)),
                ('corrente_consumida_ma', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Corrente consumida pelo sensor em mA.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade_fios', models.PositiveIntegerField(blank=True, help_text='Quantidade de fios do sensor.', null=True)),
                ('range_medicao', models.CharField(blank=True, default='', help_text='Faixa de medição (opcional).', max_length=100)),
                ('pnp', models.BooleanField(default=False)),
                ('npn', models.BooleanField(default=False)),
                ('normalmente_aberto', models.BooleanField(default=False)),
                ('normalmente_fechado', models.BooleanField(default=False)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'SENSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Sensor',
                'verbose_name_plural': 'Especificações de Sensores',
            },
        ),
        migrations.CreateModel(
            name='CargaTransdutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transdutor', models.CharField(choices=[('PRESSAO', 'Pressão'), ('TEMPERATURA', 'Temperatura'), ('NIVEL', 'Nível'), ('VAZAO', 'Vazão'), ('POSICAO', 'Posição'), ('CORRENTE', 'Corrente'), ('TENSAO', 'Tensão')], max_length=30)),
                ('faixa_medicao', models.CharField(blank=True, help_text='Ex.: 0-10 bar, 0-100 °C, 0-5 m', max_length=100)),
                ('tipo_sinal_analogico', models.CharField(blank=True, choices=[('TENSAO_0_10VCC', 'Tensão 0-10 VCC'), ('TENSAO_M10_10VCC', 'Tensão -10 a 10 VCC'), ('CORRENTE_0_20MA', 'Corrente 0-20 mA'), ('CORRENTE_4_20MA', 'Corrente 4-20 mA'), ('TEMPERATURA_PT100', 'Temperatura PT100'), ('TEMPERATURA_RTD', 'Temperatura RTD'), ('OUTROS', 'Outros')], max_length=30, null=True)),
                ('precisao', models.CharField(blank=True, default='', help_text='Ex.: precisão declarada pelo fabricante.', max_length=50)),
                ('tensao_alimentacao', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=24, help_text='Tensão de alimentação do transdutor.')),
                ('tipo_corrente', models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CC', help_text='Tipo de corrente da alimentação do transdutor.', max_length=2)),
                ('corrente_consumida_ma', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Corrente consumida pelo transdutor em mA.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade_fios', models.PositiveIntegerField(blank=True, help_text='Quantidade de fios do transdutor.', null=True)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'TRANSDUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='transdutor', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Transdutor',
                'verbose_name_plural': 'Especificações de Transdutores',
            },
        ),
        migrations.CreateModel(
            name='CargaValvula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_valvula', models.CharField(choices=[('SOLENOIDE', 'Solenóide'), ('PROPORCIONAL', 'Proporcional'), ('MOTORIZADA', 'Motorizada'), ('PNEUMATICA', 'Pneumática'), ('OUTRA', 'Outra')], default='SOLENOIDE', max_length=30)),
                ('quantidade_vias', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_posicoes', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_solenoides', models.PositiveIntegerField(default=1, help_text='Quantidade de solenoides da válvula.', validators=[django.core.validators.MinValueValidator(1)])),
                ('retorno_mola', models.BooleanField(default=False)),
                ('possui_feedback', models.BooleanField(default=False)),
                ('tensao_alimentacao', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=24, help_text='Tensão de alimentação da válvula.')),
                ('tipo_corrente', models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CC', help_text='Tipo de corrente da alimentação da válvula.', max_length=2)),
                ('corrente_consumida_ma', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Corrente consumida pela válvula em mA.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tipo_protecao', models.CharField(choices=[('MINIDISJUNTOR', 'Minidisjuntor'), ('BORNE_FUSIVEL', 'Borne Fusível'), ('SEM_PROTECAO', 'Sem proteção')], default='BORNE_FUSIVEL', help_text='Tipo de proteção elétrica da válvula.', max_length=30)),
                ('tipo_acionamento', models.CharField(choices=[('SOLENOIDE_DIRETO', 'Solenoide direto'), ('RELE_INTERFACE', 'Relé de interface'), ('CONTATOR', 'Contator')], default='SOLENOIDE_DIRETO', help_text='Tipo de acionamento da válvula.', max_length=30)),
                ('tipo_rele_interface', models.CharField(blank=True, choices=[('ELETROMECANICA', 'Eletromecânica'), ('ESTADO_SOLIDO', 'Estado sólido')], help_text='Quando o acionamento é relé de interface: eletromecânico ou estado sólido.', max_length=30, null=True)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'VALVULA'}, on_delete=django.db.models.deletion.CASCADE, related_name='valvula', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Válvula',
                'verbose_name_plural': 'Especificações de Válvulas',
            },
        ),
        migrations.AddConstraint(
            model_name='carga',
            constraint=models.UniqueConstraint(fields=('projeto', 'tag'), name='unique_tag_por_projeto'),
        ),
        migrations.AddIndex(
            model_name='cargamodelo',
            index=models.Index(fields=['ativo', 'tipo'], name='cargas_carg_ativo_87cc2d_idx'),
        ),
    ]
