# Generated by Django 5.2.1 on 2026-05-09 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargas', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionamentoCircuitoAlimentacaoGeral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('corrente_total_painel_a', models.DecimalField(decimal_places=2, help_text='Referência: ResumoDimensionamento.corrente_total_painel_a no momento do cálculo.', max_digits=12)),
                ('tipo_corrente', models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], max_length=2)),
                ('numero_fases', models.IntegerField(blank=True, help_text='Cópia de projetos_projeto.numero_fases (CA).', null=True)),
                ('possui_neutro', models.BooleanField()),
                ('possui_terra', models.BooleanField(help_text='Alimentação com condutor de proteção (PE/terra).')),
                ('quantidade_condutores_fase', models.PositiveSmallIntegerField(default=0, help_text='Condutores de fase (ou pólos ativos em CC: ex. 2).')),
                ('quantidade_condutores_neutro', models.PositiveSmallIntegerField(default=0, help_text='0 se não houver neutro; 1 se houver condutor N.')),
                ('secao_condutor_fase_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_neutro_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_pe_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_fase_escolhida_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_neutro_escolhida_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_pe_escolhida_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('condutores_aprovado', models.BooleanField(default=False, help_text='Bitolas da alimentação geral aprovadas na revisão (lista de aprovados).')),
                ('observacoes', models.TextField(blank=True)),
                ('memoria_calculo', models.TextField(blank=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionamento_alimentacao_geral', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Dimensionamento — alimentação geral do painel',
                'verbose_name_plural': 'Dimensionamentos — alimentação geral do painel',
            },
        ),
        migrations.CreateModel(
            name='DimensionamentoCircuitoCarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_carga', models.CharField(choices=[('MOTOR', 'Motor'), ('VALVULA', 'Válvula'), ('RESISTENCIA', 'Resistência'), ('SENSOR', 'Sensor'), ('TRANSDUTOR', 'Transdutor'), ('TRANSMISSOR', 'Transmissor')], db_index=True, max_length=30)),
                ('classificacao_circuito', models.CharField(choices=[('POTENCIA', 'Potência'), ('COMANDO', 'Comando'), ('SINAL', 'Sinal')], default='POTENCIA', max_length=20)),
                ('corrente_calculada_a', models.DecimalField(blank=True, decimal_places=2, help_text='Corrente por unidade ou do elemento (conforme especificação da carga).', max_digits=12, null=True)),
                ('corrente_projeto_a', models.DecimalField(blank=True, decimal_places=2, help_text='Corrente após aplicar fator de demanda do projeto (e quantidade, quando aplicável).', max_digits=12, null=True)),
                ('quantidade_condutores_fase', models.PositiveSmallIntegerField(default=0, help_text='Condutores de fase/potência ou, em comando/sinal, uso conforme regra documentada.')),
                ('quantidade_condutores_comando', models.PositiveSmallIntegerField(default=0)),
                ('quantidade_condutores_sinal', models.PositiveSmallIntegerField(default=0)),
                ('possui_neutro', models.BooleanField(default=False)),
                ('possui_pe', models.BooleanField(default=False)),
                ('secao_condutor_fase_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_neutro_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_pe_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_fase_escolhida_mm2', models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchido, substitui a seção sugerida para fase (validação Iz ≥ corrente).', max_digits=8, null=True)),
                ('secao_condutor_neutro_escolhida_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('secao_condutor_pe_escolhida_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('condutores_aprovado', models.BooleanField(default=False, help_text='Bitolas deste circuito foram aprovadas na revisão (lista de aprovados).')),
                ('observacoes', models.TextField(blank=True)),
                ('memoria_calculo', models.TextField(blank=True)),
                ('carga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionamento_circuito', to='cargas.carga')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionamentos_circuito_carga', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Dimensionamento de circuito (carga)',
                'verbose_name_plural': 'Dimensionamentos de circuitos (cargas)',
                'ordering': ['projeto', 'carga__tag'],
            },
        ),
        migrations.CreateModel(
            name='ResumoDimensionamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('corrente_total_painel_a', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('corrente_estimada_fonte_24vcc_a', models.DecimalField(decimal_places=2, default=0, help_text='Estimativa de corrente na fonte 24 Vcc (comando), com margem.', max_digits=12)),
                ('necessita_fonte_24vcc', models.BooleanField(default=False)),
                ('necessita_plc', models.BooleanField(default=False)),
                ('necessita_expansao_plc', models.BooleanField(default=False)),
                ('total_entradas_digitais', models.PositiveIntegerField(default=0)),
                ('total_saidas_digitais', models.PositiveIntegerField(default=0)),
                ('total_entradas_analogicas', models.PositiveIntegerField(default=0)),
                ('total_saidas_analogicas', models.PositiveIntegerField(default=0)),
                ('largura_painel_mm', models.PositiveIntegerField(default=0)),
                ('altura_painel_mm', models.PositiveIntegerField(default=0)),
                ('profundidade_painel_mm', models.PositiveIntegerField(default=0)),
                ('taxa_ocupacao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_montagem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('condutores_revisao_confirmada', models.BooleanField(default=False, help_text='Utilizador confirmou revisão/aprovação das bitolas de condutores no wizard.')),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumo_dimensionamento', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Resumo de Dimensionamento',
                'verbose_name_plural': 'Resumos de Dimensionamento',
            },
        ),
    ]
