# Generated by Django 5.2.12 on 2026-03-21 12:32

import core.models.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('MINI_DISJUNTOR', 'Mini disjuntor'), ('SECCIONADORA', 'Seccionadora'), ('FONTE', 'Fonte'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('BORNE', 'Borne'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros')], max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('largura_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('altura_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('profundidade_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes_tecnicas', models.TextField(blank=True)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('referencia_fabricante', models.CharField(blank=True, max_length=120)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('MT', 'Metro'), ('CJ', 'Conjunto')], default='UN', max_length=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoriaproduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['codigo', 'descricao'],
            },
            bases=(core.models.mixins.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EspecificacaoSeccionadora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('corrente_ac1_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('corrente_ac3_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_montagem', models.CharField(choices=[('TRILHO_DIN', 'Trilho DIN'), ('PLACA', 'Placa de montagem'), ('PORTA', 'Porta'), ('LATERAL', 'Lateral do painel'), ('FUNDO', 'Fundo do painel')], max_length=20)),
                ('tipo_fixacao', models.CharField(choices=[('FURO_CENTRAL_M22_5', 'Fixação por furo central M22,5'), ('QUATRO_FUROS', 'Fixação por quatro furos')], max_length=30)),
                ('cor_manopla', models.CharField(choices=[('PUNHO_PRETO', 'Punho Preto'), ('PUNHO_VERMELHO', 'Punho Vermelho')], max_length=30)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacao_seccionadora', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Especificação de Seccionadora',
                'verbose_name_plural': 'Especificações de Seccionadoras',
            },
        ),
        migrations.CreateModel(
            name='EspecificacaoDisjuntorMotor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('faixa_ajuste_min_a', models.DecimalField(decimal_places=2, max_digits=8)),
                ('faixa_ajuste_max_a', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contatos_aux_na', models.PositiveSmallIntegerField(default=0)),
                ('contatos_aux_nf', models.PositiveSmallIntegerField(default=0)),
                ('modo_montagem', models.CharField(choices=[('TRILHO_DIN', 'Trilho DIN'), ('PLACA', 'Placa de montagem'), ('PORTA', 'Porta'), ('LATERAL', 'Lateral do painel'), ('FUNDO', 'Fundo do painel')], max_length=20)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacao_disjuntor_motor', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Especificação de Disjuntor Motor',
                'verbose_name_plural': 'Especificações de Disjuntores Motores',
            },
        ),
        migrations.CreateModel(
            name='EspecificacaoContatora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('corrente_ac3_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('corrente_ac1_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tensao_bobina_v', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=24)),
                ('tipo_corrente_bobina', models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CC', max_length=2)),
                ('contatos_aux_na', models.PositiveSmallIntegerField(default=0)),
                ('contatos_aux_nf', models.PositiveSmallIntegerField(default=0)),
                ('modo_montagem', models.CharField(choices=[('TRILHO_DIN', 'Trilho DIN'), ('PLACA', 'Placa de montagem'), ('PORTA', 'Porta'), ('LATERAL', 'Lateral do painel'), ('FUNDO', 'Fundo do painel')], max_length=20)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacao_contatora', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Especificação de Contatora',
                'verbose_name_plural': 'Especificações de Contatoras',
            },
        ),
    ]
