global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_by: ["alertname", "job", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token_file: /run/secrets/telegram_bot_token
        chat_id: 8809349067
        parse_mode: HTML
        send_resolved: true
        message: |-
          {{ if eq .Status "firing" }}<b>ALERTA ATIVO</b>{{ else }}<b>ALERTA RESOLVIDO</b>{{ end }}

          <b>Status:</b> {{ .Status }}
          <b>Alertas:</b> {{ len .Alerts }}

          {{ range .Alerts }}
          <b>{{ .Labels.alertname }}</b>
          <b>Severidade:</b> {{ .Labels.severity }}
          <b>Servico:</b> {{ .Labels.job }}
          <b>Resumo:</b> {{ .Annotations.summary }}
          <b>Descricao:</b> {{ .Annotations.description }}
          {{ end }}
