# Generated by Django 5.2.1 on 2026-05-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroConfiguracao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chave', models.CharField(db_index=True, max_length=120, unique=True)),
                ('valor', models.TextField(blank=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'erp_parametro_configuracao',
                'ordering': ('chave',),
            },
        ),
    ]
