# Generated by Django 5.2.1 on 2026-05-03 18:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, help_text='Gerado automaticamente no formato MMnnn-AA (mês + sequencial + ano) ao criar.', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Nome resumido do projeto.', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do projeto.')),
                ('cliente', models.CharField(blank=True, help_text='Nome do cliente, provisoriamente em texto.', max_length=255)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='EM_ANDAMENTO', help_text='Status atual do projeto.', max_length=20)),
                ('tipo_painel', models.CharField(choices=[('AUTOMACAO', 'Automação'), ('DISTRIBUICAO', 'Distribuição')], default='AUTOMACAO', help_text='Tipo de painel do projeto.', max_length=20)),
                ('tipo_corrente', models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CA', help_text='Tipo de corrente da alimentação principal.', max_length=2)),
                ('tensao_nominal', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=380, help_text='Tensão principal do projeto/painel.')),
                ('numero_fases', models.IntegerField(blank=True, choices=[(1, 'Monofásico'), (2, 'Bifásico'), (3, 'Trifásico')], help_text='Número de fases da alimentação principal. Aplicável para CA.', null=True)),
                ('frequencia', models.IntegerField(blank=True, choices=[(50, '50 Hz'), (60, '60 Hz')], default=60, help_text='Frequência da alimentação principal. Aplicável para CA.', null=True)),
                ('possui_neutro', models.BooleanField(default=True, help_text='Indica se a alimentação principal possui neutro.')),
                ('possui_terra', models.BooleanField(default=True, help_text='Indica se a alimentação principal possui PE/terra.')),
                ('tipo_conexao_alimentacao_potencia', models.CharField(choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], default='BORNE', help_text='Tipo de conexão da alimentação de potência.', max_length=20)),
                ('tipo_conexao_alimentacao_neutro', models.CharField(blank=True, choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], help_text='Tipo de conexão do neutro da alimentação.', max_length=20, null=True)),
                ('tipo_conexao_alimentacao_terra', models.CharField(blank=True, choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], help_text='Tipo de conexão do terra da alimentação.', max_length=20, null=True)),
                ('tipo_corrente_comando', models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CC', help_text='Tipo de corrente da alimentação de comando.', max_length=2)),
                ('tensao_comando', models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=24, help_text='Tensão de alimentação do comando.')),
                ('possui_plc', models.BooleanField(default=False, help_text='Indica se o projeto possui PLC.')),
                ('familia_plc', models.CharField(blank=True, help_text='Família do PLC (catálogo EspecificacaoPLC.familia), quando o projeto possui PLC.', max_length=100, null=True)),
                ('possui_ihm', models.BooleanField(default=False, help_text='Indica se o projeto possui IHM.')),
                ('possui_switches', models.BooleanField(default=False, help_text='Indica se o projeto possui switch')),
                ('possui_plaqueta_identificacao', models.BooleanField(default=False, help_text='Indica se o projeto possui plaqueta de identificação da empresa.')),
                ('possui_faixa_identificacao', models.BooleanField(default=False, help_text='Indica se o projeto possui faixa de identificação da empresa na porta.')),
                ('possui_adesivo_alerta', models.BooleanField(default=False, help_text='Indica se o projeto possui adesivo de alerta de risco elétrico.')),
                ('possui_adesivos_tensao', models.BooleanField(default=False, help_text='Indica se o projeto possui adesivos de indicação de tensão.')),
                ('possui_climatizacao', models.BooleanField(default=False, help_text='Indica se o projeto possui climatização.')),
                ('tipo_climatizacao', models.CharField(blank=True, choices=[('VENTILADOR', 'Ventilador'), ('EXAUSTOR', 'Exaustor'), ('AR_CONDICIONADO', 'Ar Condicionado')], help_text='Tipo de climatização do painel, caso possua.', max_length=20, null=True)),
                ('fator_demanda', models.DecimalField(decimal_places=2, default='1.00', help_text='Ex.: 0.70 para 70%.', max_digits=4)),
                ('degraus_margem_bitola_condutores', models.PositiveSmallIntegerField(default=1, help_text='Margem sobre o mínimo normativo (tabela Iz): 0 = bitola mínima que atende a corrente; 1 = uma bitola comercial acima (ex.: 28 A → 4 mm² passa a 6 mm²); e assim por diante. Aplica-se ao dimensionamento sugerido de condutores de potência e da alimentação geral.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('possui_seccionamento', models.BooleanField(default=True, help_text='Indica se o projeto possui seccionamento geral.')),
                ('tipo_seccionamento', models.CharField(blank=True, choices=[('NENHUM', 'Sem seccionamento'), ('SECCIONADORA', 'Seccionadora'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada')], default='SECCIONADORA', help_text='Tipo de seccionamento geral.', max_length=30, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['codigo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modulo', models.CharField(max_length=40)),
                ('acao', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=255)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='projetos.projeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de projeto',
                'verbose_name_plural': 'Eventos de projeto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['codigo'], name='projetos_pr_codigo_89df55_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tipo_painel', 'status'], name='projetos_pr_tipo_pa_add7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tipo_corrente'], name='projetos_pr_tipo_co_3f0aca_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoevento',
            index=models.Index(fields=['projeto', '-criado_em'], name='projetos_pr_projeto_3e18f5_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoevento',
            index=models.Index(fields=['modulo', 'acao'], name='projetos_pr_modulo_86be9b_idx'),
        ),
    ]
