# Generated by Django 5.2.1 on 2026-06-07 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_objetivo_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscalEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Chave interna de deduplicação (chave NF-e ou identificador NFS-e).', max_length=120, unique=True)),
                ('tipo_documento', models.CharField(choices=[('NFE_PRODUTO', 'NF-e de produto'), ('NFSE_SERVICO', 'NFS-e de serviço')], db_index=True, max_length=20)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44)),
                ('cnpj_emitente', models.CharField(max_length=14)),
                ('nome_emitente', models.CharField(blank=True, max_length=255)),
                ('cnpj_destinatario', models.CharField(blank=True, max_length=14)),
                ('nome_destinatario', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('natureza_operacao', models.CharField(blank=True, max_length=255)),
                ('objetivo_saida', models.CharField(choices=[('VENDA_PRODUTO', 'Venda de produto'), ('PRESTACAO_SERVICO', 'Prestação de serviço'), ('INDUSTRIALIZACAO', 'Industrialização'), ('DEVOLUCAO_COMPRA', 'Devolução de compra'), ('REMESSA', 'Remessa'), ('TRANSFERENCIA', 'Transferência'), ('BONIFICACAO_DOACAO_BRINDE', 'Bonificação, doação ou brinde'), ('OUTRAS_SAIDAS', 'Outras saídas')], db_index=True, default='OUTRAS_SAIDAS', max_length=40)),
                ('origem_importacao', models.CharField(choices=[('MANUAL', 'Manual'), ('PONTE_A3', 'Ponte A3'), ('API', 'API'), ('OUTRO', 'Outro')], default='MANUAL', max_length=30)),
                ('xml_original', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento fiscal emitido',
                'verbose_name_plural': 'Documentos fiscais emitidos',
                'ordering': ['-data_emissao', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDocumentoFiscalEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(default=1)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('ncm', models.CharField(blank=True, max_length=20)),
                ('cfop', models.CharField(blank=True, max_length=10)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.documentofiscalemitido')),
            ],
            options={
                'verbose_name': 'Item do documento fiscal emitido',
                'verbose_name_plural': 'Itens dos documentos fiscais emitidos',
                'ordering': ['numero_item'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero_item'), name='fiscal_item_emitido_doc_numero_unico')],
            },
        ),
    ]
