# Generated by Django 5.2.1 on 2026-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_documentofiscalemitido_itemdocumentofiscalemitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTributarioSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('folha_salarios_12m', models.DecimalField(decimal_places=2, default=0, help_text='Folha de salários dos últimos 12 meses (Fator R).', max_digits=14)),
                ('encargos_folha_12m', models.DecimalField(decimal_places=2, default=0, help_text='INSS patronal, FGTS e contribuições sobre folha (12 meses).', max_digits=14)),
                ('anexo_servicos_override', models.CharField(blank=True, choices=[('I', 'Anexo I — Comércio'), ('II', 'Anexo II — Indústria'), ('III', 'Anexo III — Serviços'), ('V', 'Anexo V — Serviços'), ('NENHUM', 'Não compõe faturamento')], help_text='Força Anexo III ou V para serviços; vazio = calcular pelo Fator R.', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil tributário Simples Nacional',
                'verbose_name_plural': 'Perfis tributários Simples Nacional',
            },
        ),
        migrations.AddField(
            model_name='documentofiscalemitido',
            name='anexo_simples',
            field=models.CharField(blank=True, choices=[('I', 'Anexo I — Comércio'), ('II', 'Anexo II — Indústria'), ('III', 'Anexo III — Serviços'), ('V', 'Anexo V — Serviços'), ('NENHUM', 'Não compõe faturamento')], db_index=True, help_text='Vazio em serviços: resolvido pelo Fator R na projeção de DAS.', max_length=10),
        ),
        migrations.AddField(
            model_name='documentofiscalemitido',
            name='cfop_predominante',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='documentofiscalemitido',
            name='classificacao_origem',
            field=models.CharField(choices=[('AUTOMATICA', 'Automática (CFOP)'), ('MANUAL', 'Manual')], default='AUTOMATICA', max_length=20),
        ),
        migrations.AddField(
            model_name='documentofiscalemitido',
            name='incluir_faturamento',
            field=models.BooleanField(default=True, help_text='Se falso, a nota não entra na RBT12 (devolução, remessa etc.).'),
        ),
        migrations.AlterField(
            model_name='documentofiscalemitido',
            name='origem_importacao',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PONTE_A3', 'Ponte A3 (legado)'), ('SEFAZ_SYNC', 'Sincronização SEFAZ'), ('API', 'API'), ('OUTRO', 'Outro')], default='MANUAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentofiscalrecebido',
            name='manifestacao_status',
            field=models.CharField(choices=[('NAO_SOLICITADA', 'Não solicitada'), ('PENDENTE', 'Pendente (aguarda sincronização SEFAZ)'), ('MANIFESTADA', 'Registrada na SEFAZ'), ('ERRO', 'Erro na última tentativa')], default='NAO_SOLICITADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentofiscalrecebido',
            name='origem_importacao',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PONTE_A3', 'Ponte A3 (legado)'), ('SEFAZ_SYNC', 'Sincronização SEFAZ'), ('API', 'API'), ('OUTRO', 'Outro')], default='MANUAL', max_length=30),
        ),
        migrations.CreateModel(
            name='FaturamentoMensalAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('competencia', models.CharField(db_index=True, help_text='Formato AAAA-MM.', max_length=7)),
                ('valor_ajuste', models.DecimalField(decimal_places=2, default=0, help_text='Valor somado ao faturamento importado das NF-es do mês.', max_digits=14)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajuste de faturamento mensal',
                'verbose_name_plural': 'Ajustes de faturamento mensal',
                'constraints': [models.UniqueConstraint(fields=('cnpj', 'competencia'), name='fiscal_faturamento_ajuste_cnpj_competencia_unico')],
            },
        ),
    ]
