# Generated by Django 5.2.1 on 2026-06-13 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_incluir_faturamento_default_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleNsuNfseAdn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ultimo_nsu', models.CharField(default='000000000000000', max_length=15)),
                ('max_nsu', models.CharField(blank=True, max_length=15, null=True)),
                ('ultimo_status', models.CharField(blank=True, max_length=80)),
                ('ultimo_motivo', models.CharField(blank=True, max_length=255)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Controle NSU NFS-e ADN',
                'verbose_name_plural': 'Controles NSU NFS-e ADN',
            },
        ),
        migrations.CreateModel(
            name='DocumentoNfseRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('identificador', models.CharField(max_length=120, unique=True)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=50)),
                ('nsu_adn', models.CharField(blank=True, max_length=15, null=True)),
                ('cnpj_prestador', models.CharField(max_length=14)),
                ('nome_prestador', models.CharField(blank=True, max_length=255)),
                ('cnpj_tomador', models.CharField(max_length=14)),
                ('nome_tomador', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('codigo_verificacao', models.CharField(blank=True, max_length=60)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('descricao_servico', models.CharField(blank=True, max_length=500)),
                ('status_importacao', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('PROCESSADA', 'Processada'), ('ERRO', 'Erro'), ('IGNORADA', 'Ignorada')], default='RECEBIDA', max_length=30)),
                ('origem_importacao', models.CharField(choices=[('MANUAL', 'Manual'), ('PONTE_A3', 'Ponte A3 (legado)'), ('SEFAZ_SYNC', 'Sincronização SEFAZ'), ('ADN_SYNC', 'Sincronização ADN (NFS-e Nacional)'), ('API', 'API'), ('OUTRO', 'Outro')], default='MANUAL', max_length=30)),
                ('objetivo_entrada', models.CharField(choices=[('INDUSTRIALIZACAO', 'Industrialização'), ('REVENDA', 'Revenda'), ('USO_CONSUMO', 'Uso e consumo'), ('ATIVO_IMOBILIZADO', 'Ativo imobilizado'), ('DEVOLUCAO_VENDA', 'Devolução de venda'), ('RETORNO_INDUSTRIALIZACAO', 'Retorno de industrialização'), ('RETORNO_CONSERTO_REPARO', 'Retorno de conserto/reparo'), ('TRANSFERENCIA', 'Transferência'), ('BONIFICACAO_DOACAO_BRINDE', 'Bonificação, doação ou brinde'), ('AMOSTRA_GRATIS', 'Amostra grátis'), ('COMODATO_EMPRESTIMO', 'Comodato/empréstimo'), ('DEMONSTRACAO', 'Demonstração'), ('IMPORTACAO', 'Importação'), ('OUTRAS_ENTRADAS', 'Outras entradas')], db_index=True, default='OUTRAS_ENTRADAS', max_length=40)),
                ('xml_original', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NFS-e recebida',
                'verbose_name_plural': 'NFS-es recebidas',
                'ordering': ['-data_emissao', '-criada_em'],
            },
        ),
        migrations.AlterField(
            model_name='documentofiscalemitido',
            name='origem_importacao',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PONTE_A3', 'Ponte A3 (legado)'), ('SEFAZ_SYNC', 'Sincronização SEFAZ'), ('ADN_SYNC', 'Sincronização ADN (NFS-e Nacional)'), ('API', 'API'), ('OUTRO', 'Outro')], default='MANUAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentofiscalrecebido',
            name='origem_importacao',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PONTE_A3', 'Ponte A3 (legado)'), ('SEFAZ_SYNC', 'Sincronização SEFAZ'), ('ADN_SYNC', 'Sincronização ADN (NFS-e Nacional)'), ('API', 'API'), ('OUTRO', 'Outro')], default='MANUAL', max_length=30),
        ),
        migrations.CreateModel(
            name='ItemDocumentoNfseRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.documentonfserecebido')),
            ],
            options={
                'verbose_name': 'Item da NFS-e recebida',
                'verbose_name_plural': 'Itens das NFS-es recebidas',
                'ordering': ['numero_item'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero_item'), name='fiscal_item_nfse_recebida_doc_numero_unico')],
            },
        ),
    ]
