# Generated by Django 5.2.15 on 2026-06-14 00:22

import apps.fiscal.models_obrigacoes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_nfse_recebida_adn'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('DAS', 'DAS (Simples Nacional)'), ('INSS_DARF', 'INSS (DARF)'), ('FGTS', 'FGTS'), ('ISS', 'ISS municipal'), ('ICMS', 'ICMS (apuração)'), ('OUTRO', 'Outro')], db_index=True, max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado pelo ERP (projeção/conciliação).', max_digits=14, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('dados_extra', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento_fiscal_emitido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obrigacoes_iss', to='fiscal.documentofiscalemitido')),
            ],
            options={
                'verbose_name': 'Obrigação fiscal',
                'verbose_name_plural': 'Obrigações fiscais',
                'ordering': ['data_vencimento', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='LinhaComposicaoObrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_composicao', to='fiscal.obrigacaofiscal')),
            ],
            options={
                'verbose_name': 'Linha de composição de obrigação',
                'verbose_name_plural': 'Linhas de composição de obrigação',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiroImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField()),
                ('conta', models.CharField(blank=True, default='Impostos', max_length=80)),
                ('centro_custo', models.CharField(blank=True, default='Administrativo', max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obrigacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lancamento_financeiro', to='fiscal.obrigacaofiscal')),
            ],
            options={
                'verbose_name': 'Lançamento financeiro de imposto',
                'verbose_name_plural': 'Lançamentos financeiros de impostos',
            },
        ),
        migrations.CreateModel(
            name='PacoteObrigacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('competencia', models.CharField(db_index=True, help_text='Formato AAAA-MM.', max_length=7)),
                ('recebido_em', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('pacote_completo', models.BooleanField(default=False, help_text='Marcado quando todos os documentos esperados foram recebidos.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pacote de obrigações fiscais',
                'verbose_name_plural': 'Pacotes de obrigações fiscais',
                'ordering': ['-competencia'],
                'constraints': [models.UniqueConstraint(fields=('cnpj', 'competencia'), name='fiscal_pacote_obrigacao_cnpj_competencia_unico')],
            },
        ),
        migrations.AddField(
            model_name='obrigacaofiscal',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes', to='fiscal.pacoteobrigacaofiscal'),
        ),
        migrations.CreateModel(
            name='HoleriteCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14)),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('CLT', 'CLT'), ('PRO_LABORE', 'Pró-labore'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('proventos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_inss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_fgts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fgts_mes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dados_extra', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holerites_fiscais', to='rh.colaborador')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holerites', to='fiscal.pacoteobrigacaofiscal')),
            ],
            options={
                'verbose_name': 'Holerite da competência',
                'verbose_name_plural': 'Holerites da competência',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AnexoObrigacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_arquivo', models.CharField(choices=[('DARF', 'DARF'), ('FGTS', 'FGTS'), ('ISS', 'ISS'), ('DIME_ICMS', 'DIME ICMS'), ('SIMPLES', 'Simples Nacional'), ('HOLERITE', 'Holerite / folha'), ('COMPROVANTE', 'Comprovante de pagamento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('arquivo', models.FileField(upload_to=apps.fiscal.models_obrigacoes.obrigacao_anexo_upload_to)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('parse_sucesso', models.BooleanField(default=False)),
                ('parse_erros', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obrigacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='fiscal.obrigacaofiscal')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='fiscal.pacoteobrigacaofiscal')),
            ],
            options={
                'verbose_name': 'Anexo de obrigação fiscal',
                'verbose_name_plural': 'Anexos de obrigações fiscais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotApuracaoIcms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_credor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('debitos_saidas', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creditos_entradas', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_debitos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('saldo_credor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('imposto_a_recolher', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_contabil_entradas', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_contabil_saidas', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dados_quadros', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pacote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_icms', to='fiscal.pacoteobrigacaofiscal')),
            ],
            options={
                'verbose_name': 'Snapshot apuração ICMS',
                'verbose_name_plural': 'Snapshots apuração ICMS',
            },
        ),
        migrations.CreateModel(
            name='ReconciliacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DAS', 'DAS estimado × contabilidade'), ('INSS', 'INSS DARF × holerites'), ('FGTS', 'FGTS guia × holerites'), ('ISS', 'ISS guia × NFS-e'), ('ICMS', 'ICMS DIME × movimento NF-e'), ('PACOTE', 'Pacote mensal completo')], max_length=20)),
                ('valor_interno', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_contabilidade', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('diferenca_percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ALERTA', 'Alerta'), ('ERRO', 'Erro'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliacoes', to='fiscal.pacoteobrigacaofiscal')),
            ],
            options={
                'verbose_name': 'Reconciliação fiscal',
                'verbose_name_plural': 'Reconciliações fiscais',
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(fields=('pacote', 'tipo'), name='fiscal_reconciliacao_pacote_tipo_unico')],
            },
        ),
    ]
