# Generated by Django 5.2.1 on 2026-06-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_remove_produto_fabricante'),
        ('fiscal', '0012_documento_sefaz_distribuido'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscalrecebido',
            name='cfop_predominante',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='documentofiscalrecebido',
            name='classificacao_origem',
            field=models.CharField(choices=[('AUTOMATICA', 'Automática (CFOP)'), ('MANUAL', 'Manual')], default='AUTOMATICA', max_length=20),
        ),
        migrations.AddField(
            model_name='documentofiscalrecebido',
            name='finalidade_nfe',
            field=models.CharField(blank=True, choices=[('1', 'Normal'), ('2', 'Complementar'), ('3', 'Ajuste'), ('4', 'Devolução/retorno')], db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='itemdocumentofiscal',
            name='classificacao_origem',
            field=models.CharField(choices=[('AUTOMATICA', 'Automática (CFOP)'), ('MANUAL', 'Manual')], default='AUTOMATICA', max_length=20),
        ),
        migrations.AddField(
            model_name='itemdocumentofiscal',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
        migrations.AddField(
            model_name='itemdocumentofiscal',
            name='objetivo_entrada',
            field=models.CharField(choices=[('INDUSTRIALIZACAO', 'Industrialização'), ('REVENDA', 'Revenda'), ('USO_CONSUMO', 'Uso e consumo'), ('ATIVO_IMOBILIZADO', 'Ativo imobilizado'), ('DEVOLUCAO_VENDA', 'Devolução de venda'), ('RETORNO_INDUSTRIALIZACAO', 'Retorno de industrialização'), ('RETORNO_CONSERTO_REPARO', 'Retorno de conserto/reparo'), ('TRANSFERENCIA', 'Transferência'), ('BONIFICACAO_DOACAO_BRINDE', 'Bonificação, doação ou brinde'), ('AMOSTRA_GRATIS', 'Amostra grátis'), ('COMODATO_EMPRESTIMO', 'Comodato/empréstimo'), ('DEMONSTRACAO', 'Demonstração'), ('IMPORTACAO', 'Importação'), ('OUTRAS_ENTRADAS', 'Outras entradas')], db_index=True, default='OUTRAS_ENTRADAS', max_length=40),
        ),
        migrations.AddField(
            model_name='itemdocumentofiscal',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_documento_fiscal', to='catalogo.produto'),
        ),
        migrations.AlterField(
            model_name='reconciliacaofiscal',
            name='tipo',
            field=models.CharField(choices=[('DAS', 'DAS estimado × contabilidade'), ('DAS_INSS', 'INSS DAS (1006) × holerites'), ('INSS', 'INSS DARF × holerites'), ('FGTS', 'FGTS guia × holerites'), ('ISS', 'ISS guia × NFS-e'), ('ICMS', 'ICMS DIME × movimento NF-e'), ('PACOTE', 'Pacote mensal completo')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProdutoFornecedorXRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_fornecedor', models.CharField(db_index=True, max_length=14)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=255)),
                ('codigo_fornecedor', models.CharField(db_index=True, max_length=100)),
                ('gtin', models.CharField(blank=True, db_index=True, max_length=14)),
                ('descricao_fornecedor', models.CharField(blank=True, max_length=500)),
                ('unidade_fornecedor', models.CharField(blank=True, max_length=20)),
                ('ncm_fornecedor', models.CharField(blank=True, max_length=20)),
                ('origem', models.CharField(choices=[('AUTOMATICA', 'Automática (CFOP)'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_fornecedor', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'De-para produto×fornecedor',
                'verbose_name_plural': 'De-para produto×fornecedor',
                'ordering': ['cnpj_fornecedor', 'codigo_fornecedor'],
                'constraints': [models.UniqueConstraint(fields=('cnpj_fornecedor', 'codigo_fornecedor'), name='fiscal_xref_fornecedor_codigo_unico')],
            },
        ),
    ]
