# Generated by Django 5.2.12 on 2026-03-20 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0007_projeto_possui_adesivo_alerta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoDimensionamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('corrente_total_painel_a', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('necessita_fonte_24vcc', models.BooleanField(default=False)),
                ('necessita_plc', models.BooleanField(default=False)),
                ('necessita_expansao_plc', models.BooleanField(default=False)),
                ('total_entradas_digitais', models.PositiveIntegerField(default=0)),
                ('total_saidas_digitais', models.PositiveIntegerField(default=0)),
                ('total_entradas_analogicas', models.PositiveIntegerField(default=0)),
                ('total_saidas_analogicas', models.PositiveIntegerField(default=0)),
                ('largura_painel_mm', models.PositiveIntegerField(default=0)),
                ('altura_painel_mm', models.PositiveIntegerField(default=0)),
                ('profundidade_painel_mm', models.PositiveIntegerField(default=0)),
                ('taxa_ocupacao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_montagem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumo_dimensionamento', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Resumo de Dimensionamento',
                'verbose_name_plural': 'Resumos de Dimensionamento',
            },
        ),
    ]
