# Generated by Django 5.2.12 on 2026-03-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumodimensionamento',
            name='corrente_estimada_fonte_24vcc_a',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimativa de corrente na fonte 24 Vcc (comando), com margem.', max_digits=12),
        ),
    ]
