# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimensionamento", "0005_condutores_escolha_e_confirmacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensionamentocircuitocarga",
            name="condutores_aprovado",
            field=models.BooleanField(
                default=False,
                help_text="Bitolas deste circuito foram aprovadas na revisão (lista de aprovados).",
            ),
        ),
        migrations.AddField(
            model_name="dimensionamentocircuitoalimentacaogeral",
            name="condutores_aprovado",
            field=models.BooleanField(
                default=False,
                help_text="Bitolas da alimentação geral aprovadas na revisão (lista de aprovados).",
            ),
        ),
    ]
