from .cargas import (
    TipoCargaChoices,
    TipoPartidaMotorChoices,
    TipoProtecaoMotorChoices,
    TipoProtecaoResistenciaChoices,
    TipoAcionamentoResistenciaChoices,
    TipoValvulaChoices,
    TipoProtecaoValvulaChoices,
    TipoAcionamentoValvulaChoices,
    TipoSensorChoices,
    TipoTransdutorChoices,
    TipoConexaoCargaPainelChoices,
    TipoClimatizacaoPainelChoices,
)

from .eletrica import (
    TensaoChoices,
    TipoCorrenteChoices,
    UnidadePotenciaCorrenteChoices,
    NumeroFasesChoices,
    FrequenciaChoices,
    TipoSinalChoices,
    TipoSinaisAnalogicosChoices,
)

from .produtos import (
    CategoriaProdutoNomeChoices,
    TipoFusivelChoices,
    ClasseUtilizacaoFusivelChoices,
    FusivelNHTamanhoChoices,
    FusivelCartuchoTamanhoChoices,
    FormatoFusivelChoices,
    ModoMontagemChoices,
    ModoMontagemReleSobrecargaChoices,
    TipoFixacaoSeccionadoraChoices,
    CorManoplaChoices,
    UnidadeMedidaChoices,
    TipoModuloExpansaoPLCChoices,
    TipoModuloComunicacaoChoices,
    TipoAcionamentoBotaoChoices,
    CorSinalizadorChoices,
    CurvaDisparoMiniDisjuntorChoices,
    NumeroPolosChoices,
    PadraoNormativoMiniDisjuntorChoices,
    TipoProtecaoMiniDisjuntorChoices,
    TipoComutacaoReleEstadoSolidoChoices,
    TipoDissipadorReleEstadoSolidoChoices,
    NumeroFasesReleEstadoSolidoChoices,
    TipoCargaReleEstadoSolidoChoices,
    MaterialBarramentoChoices,
    TipoBarramentoChoices,
    TipoBorneChoices,
    TipoConexaoBorneChoices,
    TipoBotaoChoices,
    TipoAcionamentoBotaoModoChoices,
    CorBotaoChoices,
    TipoCaboChoices,
    MaterialCondutorChoices,
    TipoIsolacaoCaboChoices,
    CorCaboChoices,
    TipoCanaletaChoices,
    MaterialCanaletaChoices,
    CorCanaletaChoices,
    TipoChaveSeletoraChoices,
    TipoAcionamentoChaveSeletoraChoices,
    CorManoplaChaveSeletoraChoices,
    TipoClimatizacaoChoices,
    TipoSensorTemperaturaChoices,
    TipoSaidaControleChoices,
    TipoControleTemperaturaChoices,
    TipoExpansaoPLCChoices,
    TipoSinalDigitalChoices,
    TipoSinalAnalogicoChoices,
    TipoAnalogicoPlcChoices,
    TipoFiltroArChoices,
    MaterialFiltroArChoices,
    ProtocoloIndustrialChoices,
    InterfaceFisicaGatewayChoices,
    TipoTelaIHMChoices,
    TipoDisplayIHMChoices,
    ProtocoloIHMChoices,
    TipoPLCChoices,
    FamiliaPLCChoices,
    ProtocoloComunicacaoChoices,
    TipoMontagemReleChoices,
    TipoContatoChoices,
    TipoReleInterfaceChoices,
    TipoResistenciaAquecimentoChoices,
    TipoMontagemResistenciaChoices,
    TipoControleSoftStarterChoices,
    TipoAplicacaoSoftStarterChoices,
    TipoBypassChoices,
    NumeroFaseControleSoftStarterChoices,
    TipoSwitchRedeChoices,
    TipoPortaRedeChoices,
    VelocidadePortaRedeChoices,
    TipoMontagemSwitchChoices,
    TipoTemporizadorChoices,
    TipoFuncaoTemporizadorChoices,
    UnidadeTempoChoices,
    TipoMontagemTemporizadorChoices,
    TipoTrilhoDINChoices,
    FormatoTrilhoDINChoices,
    MaterialTrilhoDINChoices,
    TipoVentiladorChoices,
    TipoMontagemVentiladorChoices,
)

from .paineis import (
    TipoPainelChoices,
    TipoPainelCatalogoChoices,
    TipoInstalacaoPainelChoices,
    MaterialPainelChoices,
    AcabamentoPlacaPainelChoices,
    CorPainelChoices,
    TipoSeccionamentoChoices,
    TipoConexaoAlimetacaoChoices,
    PartesPainelChoices,
    StatusProjetoChoices,
    
)

from .gerais import (
    OrigemItemChoices,
    StatusSugestaoChoices,
    StatusPendenciaChoices,
)   

from .usuarios import (
    DEFAULT_PERMISSIONS_BY_TIPO,
    PermissaoUsuarioChoices,
    TipoUsuarioChoices,
)


__all__ = [
  # ELÉTRICA
    "TensaoChoices",
    "TipoCorrenteChoices",
    "UnidadePotenciaCorrenteChoices",
    "NumeroFasesChoices",
    "FrequenciaChoices",
    "TipoSinalChoices",
    "TipoSinaisAnalogicosChoices",

    # CARGAS
    "TipoCargaChoices",
    "TipoPartidaMotorChoices",
    "TipoProtecaoMotorChoices",
    "TipoProtecaoResistenciaChoices",
    "TipoAcionamentoResistenciaChoices",
    "TipoValvulaChoices",
    "TipoProtecaoValvulaChoices",
    "TipoAcionamentoValvulaChoices",
    "TipoSensorChoices",
    "TipoTransdutorChoices",
    "TipoConexaoCargaPainelChoices",
    "TipoClimatizacaoPainelChoices",
    

    # PRODUTOS
    "CategoriaProdutoNomeChoices",
    "TipoFusivelChoices",
    "ClasseUtilizacaoFusivelChoices",
    "FusivelNHTamanhoChoices",
    "FusivelCartuchoTamanhoChoices",
    "FormatoFusivelChoices",
    "ModoMontagemChoices",
    "ModoMontagemReleSobrecargaChoices",
    "TipoFixacaoSeccionadoraChoices",
    "CorManoplaChoices",
    "UnidadeMedidaChoices",
    "TipoModuloExpansaoPLCChoices",
    "TipoModuloComunicacaoChoices",
    "TipoAcionamentoBotaoChoices",
    "CorSinalizadorChoices",
    "CurvaDisparoMiniDisjuntorChoices",
    "NumeroPolosChoices",
    "PadraoNormativoMiniDisjuntorChoices",
    "TipoProtecaoMiniDisjuntorChoices",
    "TipoComutacaoReleEstadoSolidoChoices",
    "TipoDissipadorReleEstadoSolidoChoices",
    "NumeroFasesReleEstadoSolidoChoices",
    "TipoCargaReleEstadoSolidoChoices",
    "MaterialBarramentoChoices",
    "TipoBarramentoChoices",
    "TipoBorneChoices",
    "TipoConexaoBorneChoices",
    "TipoBotaoChoices",
    "TipoAcionamentoBotaoModoChoices",
    "CorBotaoChoices",
    "TipoCaboChoices",
    "MaterialCondutorChoices",
    "TipoIsolacaoCaboChoices",
    "CorCaboChoices",
    "TipoCanaletaChoices",
    "MaterialCanaletaChoices",
    "CorCanaletaChoices",
    "TipoChaveSeletoraChoices",
    "TipoAcionamentoChaveSeletoraChoices",
    "CorManoplaChaveSeletoraChoices",
    "TipoClimatizacaoChoices",
    "TipoSensorTemperaturaChoices",
    "TipoSaidaControleChoices",
    "TipoControleTemperaturaChoices",
    "TipoExpansaoPLCChoices",
    "TipoSinalDigitalChoices",
    "TipoSinalAnalogicoChoices",
    "TipoAnalogicoPlcChoices",
    "TipoFiltroArChoices",
    "MaterialFiltroArChoices",
    "ProtocoloIndustrialChoices",
    "InterfaceFisicaGatewayChoices",
    "TipoTelaIHMChoices",
    "TipoDisplayIHMChoices",
    "ProtocoloIHMChoices",
    "TipoPLCChoices",
    "FamiliaPLCChoices",
    "ProtocoloComunicacaoChoices",
    "TipoMontagemReleChoices",
    "TipoContatoChoices",
    "TipoReleInterfaceChoices",
    "TipoResistenciaAquecimentoChoices",
    "TipoMontagemResistenciaChoices",
    "TipoControleSoftStarterChoices",
    "TipoAplicacaoSoftStarterChoices",
    "TipoBypassChoices",
    "NumeroFaseControleSoftStarterChoices",
    "TipoSwitchRedeChoices",
    "TipoPortaRedeChoices",
    "VelocidadePortaRedeChoices",
    "TipoMontagemSwitchChoices",
    "TipoTemporizadorChoices",
    "TipoFuncaoTemporizadorChoices",
    "UnidadeTempoChoices",
    "TipoMontagemTemporizadorChoices",
    "TipoTrilhoDINChoices",
    "FormatoTrilhoDINChoices",
    "MaterialTrilhoDINChoices",
    "TipoVentiladorChoices",
    "TipoMontagemVentiladorChoices",

    # PAINÉIS
    "TipoPainelChoices",
    "TipoPainelCatalogoChoices",
    "TipoInstalacaoPainelChoices",
    "MaterialPainelChoices",
    "AcabamentoPlacaPainelChoices",
    "CorPainelChoices",
    "TipoSeccionamentoChoices",
    "TipoConexaoAlimetacaoChoices",
    "StatusProjetoChoices",
    "PartesPainelChoices",
    # GERAIS
    "OrigemItemChoices",
    "StatusSugestaoChoices",
    "StatusPendenciaChoices",
    
    # USUÁRIOS
    "TipoUsuarioChoices",
    "PermissaoUsuarioChoices",
    "DEFAULT_PERMISSIONS_BY_TIPO",
]