/** Rotas do módulo fiscal (NF-e recebidas, itens, NSU). */
export const fiscalPaths = {
  home: '/fiscal',
  itensFiscais: '/fiscal/itens-fiscais',
  nfes: '/fiscal/nfes',
  sefazDistribuicao: '/fiscal/sefaz-distribuicao',
  nfseRecebidas: '/fiscal/nfse-recebidas',
  obrigacoes: '/fiscal/obrigacoes',
  obrigacaoCompetencia: (competencia: string) => `/fiscal/obrigacoes/${competencia}`,
  relatorioNfes: '/fiscal/relatorios/nfes',
  relatorioFaturamento: '/fiscal/relatorios/faturamento',
  nfesEmitidas: '/fiscal/nfes-emitidas',
  nfeEmitidaDetalhe: (id: number | string) => `/fiscal/nfes-emitidas/${id}`,
  nfeEmitidaImportar: '/fiscal/nfes-emitidas/importar',
  projecaoDas: '/fiscal/simples/projecao-das',
  nfeDetalhe: (id: number | string) => `/fiscal/nfes/${id}`,
  nfeImportarCatalogo: (id: number | string) => `/fiscal/nfes/${id}/importar-catalogo`,
  nfseRecebidaDetalhe: (publicId: string) => `/fiscal/nfse-recebidas/${publicId}`,
  nfeImportarManual: '/fiscal/nfes/importar',
  nfeBuscarChave: '/fiscal/nfes/buscar-chave',
  nsu: '/fiscal/nsu',
} as const
