"""Rotas REST do módulo fiscal."""
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from apps.fiscal.api.fiscal_config_views import FiscalModuloConfigView
from apps.fiscal.api.manifestacao_views import (
    SolicitarManifestacaoDocumentoSefazView,
    SolicitarManifestacaoView,
)
from apps.fiscal.api.relatorio_faturamento_views import RelatorioFaturamentoView
from apps.fiscal.api.sefaz_sync_views import (
    ImportarNfePorChaveSefazView,
    SincronizarNfesSefazView,
)
from apps.fiscal.api.nfse_recebida_views import (
    ControleNsuNfseAdnView,
    DocumentoNfseRecebidoViewSet,
    SincronizarNfseAdnView,
)
from apps.fiscal.api.simples_views import (
    ClassificacaoDocumentoEmitidoView,
    FaturamentoMensalAjusteView,
    FaturamentoSimplesView,
    ImportarLoteDocumentosEmitidosView,
    PerfilTributarioSimplesView,
    ProjecaoDasSimplesView,
    ReclassificarDocumentosEmitidosView,
)
from apps.fiscal.api.nfe_views import (
    ControleNSUEditarView,
    ControleNSUView,
    DocumentoFiscalEmitidoViewSet,
    DocumentoFiscalRecebidoViewSet,
    DocumentoSefazDistribuidoViewSet,
    ImportarXMLDocumentoEmitidoPortalView,
    ImportarCatalogoNFeView,
    ImportarXMLNFePortalView,
    PreviewCatalogoNFeView,
    ReclassificarEntradaView,
    RelatorioNFeView,
    VincularProdutoItemView,
)
from apps.fiscal.api.obrigacoes_views import (
    AnexoObrigacaoFiscalDetailView,
    ConciliarHoleritesRhPacoteView,
    CriarColaboradoresHoleritesPacoteView,
    CriarPacoteObrigacaoView,
    DashboardObrigacoesView,
    ExcluirTodosAnexosPacoteView,
    HoleriteCompetenciaDetailView,
    ObrigacaoFiscalDetailView,
    PacoteObrigacaoFiscalViewSet,
    ReconciliarPacoteView,
    ReconciliacaoContabilidadeView,
    UploadAnexoPacoteView,
    UploadLotePacoteView,
)
from apps.fiscal.api.views import ItemFiscalProdutoViewSet

router = DefaultRouter()
router.register(
    r"fiscal/itens-fiscais",
    ItemFiscalProdutoViewSet,
    basename="fiscal-itens-fiscais",
)
router.register(
    r"fiscal/nfes",
    DocumentoFiscalRecebidoViewSet,
    basename="fiscal-nfes",
)
router.register(
    r"fiscal/nfes-emitidas",
    DocumentoFiscalEmitidoViewSet,
    basename="fiscal-nfes-emitidas",
)
router.register(
    r"fiscal/sefaz-distribuicao",
    DocumentoSefazDistribuidoViewSet,
    basename="fiscal-sefaz-distribuicao",
)
router.register(
    r"fiscal/obrigacoes/pacotes",
    PacoteObrigacaoFiscalViewSet,
    basename="fiscal-obrigacoes-pacotes",
)
router.register(
    r"fiscal/nfse-recebidas",
    DocumentoNfseRecebidoViewSet,
    basename="fiscal-nfse-recebidas",
)

urlpatterns = [
    path(
        "fiscal/config/",
        FiscalModuloConfigView.as_view(),
        name="fiscal-config",
    ),
    path(
        "fiscal/nfes/<int:documento_id>/solicitar-manifestacao/",
        SolicitarManifestacaoView.as_view(),
        name="fiscal-nfe-solicitar-manifestacao",
    ),
    path(
        "fiscal/sefaz-distribuicao/<int:documento_id>/solicitar-manifestacao/",
        SolicitarManifestacaoDocumentoSefazView.as_view(),
        name="fiscal-sefaz-distribuicao-solicitar-manifestacao",
    ),
    path(
        "fiscal/nfes/<int:documento_id>/reclassificar/",
        ReclassificarEntradaView.as_view(),
        name="fiscal-nfe-reclassificar",
    ),
    path(
        "fiscal/nfes/<int:documento_id>/preview-catalogo/",
        PreviewCatalogoNFeView.as_view(),
        name="fiscal-nfe-preview-catalogo",
    ),
    path(
        "fiscal/nfes/<int:documento_id>/importar-catalogo/",
        ImportarCatalogoNFeView.as_view(),
        name="fiscal-nfe-importar-catalogo",
    ),
    path(
        "fiscal/itens-nfe/<int:item_id>/vincular-produto/",
        VincularProdutoItemView.as_view(),
        name="fiscal-item-nfe-vincular-produto",
    ),
    path(
        "fiscal/nfes/importar-manual/",
        ImportarXMLNFePortalView.as_view(),
        name="fiscal-nfes-importar-manual",
    ),
    path(
        "fiscal/nfes-emitidas/importar-manual/",
        ImportarXMLDocumentoEmitidoPortalView.as_view(),
        name="fiscal-nfes-emitidas-importar-manual",
    ),
    path(
        "fiscal/relatorios/nfes/",
        RelatorioNFeView.as_view(),
        name="fiscal-relatorio-nfes",
    ),
    path(
        "fiscal/relatorios/faturamento/",
        RelatorioFaturamentoView.as_view(),
        name="fiscal-relatorio-faturamento",
    ),
    path(
        "fiscal/nsu/<str:cnpj>/editar/",
        ControleNSUEditarView.as_view(),
        name="fiscal-nsu-editar",
    ),
    path(
        "fiscal/nsu/<str:cnpj>/",
        ControleNSUView.as_view(),
        name="fiscal-nsu",
    ),
    path(
        "fiscal/nfes/sincronizar-sefaz/",
        SincronizarNfesSefazView.as_view(),
        name="fiscal-nfes-sincronizar-sefaz",
    ),
    path(
        "fiscal/nfes/importar-por-chave/",
        ImportarNfePorChaveSefazView.as_view(),
        name="fiscal-nfes-importar-por-chave",
    ),
    path(
        "fiscal/nfse-recebidas/sincronizar-adn/",
        SincronizarNfseAdnView.as_view(),
        name="fiscal-nfse-recebidas-sincronizar-adn",
    ),
    path(
        "fiscal/nsu-nfse-adn/<str:cnpj_raw>/",
        ControleNsuNfseAdnView.as_view(),
        name="fiscal-nsu-nfse-adn",
    ),
    path(
        "fiscal/nfes-emitidas/importar-lote/",
        ImportarLoteDocumentosEmitidosView.as_view(),
        name="fiscal-nfes-emitidas-importar-lote",
    ),
    path(
        "fiscal/nfes-emitidas/reclassificar/",
        ReclassificarDocumentosEmitidosView.as_view(),
        name="fiscal-nfes-emitidas-reclassificar",
    ),
    path(
        "fiscal/nfes-emitidas/<uuid:public_id>/classificacao/",
        ClassificacaoDocumentoEmitidoView.as_view(),
        name="fiscal-nfe-emitida-classificacao",
    ),
    path(
        "fiscal/simples/perfil/",
        PerfilTributarioSimplesView.as_view(),
        name="fiscal-simples-perfil",
    ),
    path(
        "fiscal/simples/faturamento/",
        FaturamentoSimplesView.as_view(),
        name="fiscal-simples-faturamento",
    ),
    path(
        "fiscal/simples/projecao-das/",
        ProjecaoDasSimplesView.as_view(),
        name="fiscal-simples-projecao-das",
    ),
    path(
        "fiscal/simples/faturamento-ajuste/",
        FaturamentoMensalAjusteView.as_view(),
        name="fiscal-simples-faturamento-ajuste",
    ),
    path(
        "fiscal/obrigacoes/dashboard/",
        DashboardObrigacoesView.as_view(),
        name="fiscal-obrigacoes-dashboard",
    ),
    path(
        "fiscal/obrigacoes/pacotes/criar/",
        CriarPacoteObrigacaoView.as_view(),
        name="fiscal-obrigacoes-pacotes-criar",
    ),
    path(
        "fiscal/obrigacoes/pacotes/<uuid:public_id>/upload/",
        UploadAnexoPacoteView.as_view(),
        name="fiscal-obrigacoes-pacote-upload",
    ),
    path(
        "fiscal/obrigacoes/pacotes/<uuid:public_id>/upload-lote/",
        UploadLotePacoteView.as_view(),
        name="fiscal-obrigacoes-pacote-upload-lote",
    ),
    path(
        "fiscal/obrigacoes/pacotes/<uuid:public_id>/reconciliar/",
        ReconciliarPacoteView.as_view(),
        name="fiscal-obrigacoes-pacote-reconciliar",
    ),
    path(
        "fiscal/obrigacoes/pacotes/<uuid:public_id>/reconciliacoes/<str:tipo>/contabilidade/",
        ReconciliacaoContabilidadeView.as_view(),
        name="fiscal-obrigacoes-reconciliacao-contabilidade",
    ),
    path(
        "fiscal/obrigacoes/itens/<uuid:public_id>/",
        ObrigacaoFiscalDetailView.as_view(),
        name="fiscal-obrigacao-detail",
    ),
    path(
        "fiscal/obrigacoes/anexos/<uuid:public_id>/",
        AnexoObrigacaoFiscalDetailView.as_view(),
        name="fiscal-obrigacao-anexo-detail",
    ),
    path(
        "fiscal/obrigacoes/pacotes/<uuid:public_id>/anexos/",
        ExcluirTodosAnexosPacoteView.as_view(),
        name="fiscal-obrigacoes-pacote-anexos-excluir-todos",
    ),
    path(
        "fiscal/obrigacoes/holerites/<int:holerite_id>/",
        HoleriteCompetenciaDetailView.as_view(),
        name="fiscal-obrigacao-holerite-detail",
    ),
    path(
        "fiscal/obrigacoes/pacotes/<uuid:public_id>/holerites/conciliar-rh/",
        ConciliarHoleritesRhPacoteView.as_view(),
        name="fiscal-obrigacoes-holerites-conciliar-rh",
    ),
    path(
        "fiscal/obrigacoes/pacotes/<uuid:public_id>/holerites/criar-colaboradores/",
        CriarColaboradoresHoleritesPacoteView.as_view(),
        name="fiscal-obrigacoes-holerites-criar-colaboradores",
    ),
    path("", include(router.urls)),
]
