# Generated by Django 5.2.1 on 2026-05-09 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargas', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoInclusaoManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusoes_manuais_composicao', to='catalogo.produto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_inclusoes_manuais', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Inclusão manual (catálogo)',
                'verbose_name_plural': 'Inclusões manuais (catálogo)',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComposicaoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parte_painel', models.CharField(choices=[('SECCIONAMENTO', 'Seccionamento'), ('PROTECAO_GERAL', 'Proteção geral'), ('PROTECAO_CARGA', 'Proteção de carga'), ('ACIONAMENTO_CARGA', 'Acionamento de carga'), ('ENTRADA_PRINCIPAL', 'Entrada principal'), ('POTENCIA', 'Potência'), ('COMANDO', 'Comando'), ('BOTOEIRAS', 'Botoeiras'), ('AUTOMACAO', 'Automação'), ('BORNES', 'Bornes'), ('CANALETAS', 'Canaletas'), ('CLIMATIZACAO', 'Climatização'), ('ILUMINACAO', 'Iluminação'), ('TOMADA_SERVICO', 'Tomada de serviço'), ('ESTRUTURA', 'Estrutura'), ('IDENTIFICACAO', 'Identificação'), ('ACESSORIOS', 'Acessórios'), ('OUTROS', 'Outros')], max_length=50)),
                ('categoria_produto', models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada'), ('MINIDISJUNTOR', 'Minidisjuntor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('SECCIONADORA', 'Seccionadora'), ('FUSIVEL', 'Fusível'), ('RELE_ESTADO_SOLIDO', 'Relé Estado Sólido'), ('INVERSOR_FREQUENCIA', 'Inversor de Frequência'), ('SOFT_STARTER', 'Soft Starter'), ('BOTAO', 'Botão de Comando'), ('CHAVE_SELETORA', 'Chave Seletora'), ('SINALIZADOR', 'Sinaleiro'), ('RELE_INTERFACE', 'Relé de Interface'), ('TEMPORIZADOR', 'Relé Temporizador'), ('CONTROLADOR_TEMPERATURA', 'Controlador de Temperatura'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('IHM', 'Interface Homem Máquina (IHM)'), ('MODULO_COMUNICACAO', 'Módulo de Comunicação'), ('GATEWAY', 'Gateway'), ('SWITCH_REDE', 'Switch Industrial'), ('FONTE_CHAVEADA', 'Fonte Chaveada'), ('BORNE', 'Borne'), ('BARRAMENTO', 'Barramento'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('TRILHO_DIN', 'Trilho DIN'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros'), ('SEM_REGRA_SUGESTAO_AUTOMATICA', 'Sem regra de sugestão automática')], max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('corrente_referencia_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memoria_calculo', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('indice_escopo', models.PositiveSmallIntegerField(default=0, help_text='Índice para vários itens da mesma categoria por carga (ex.: K1/K2/K3).')),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composicao_itens', to='cargas.carga')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_itens', to='catalogo.produto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_itens', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Item da Composição',
                'verbose_name_plural': 'Itens da Composição',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto'), name='uq_composicao_item_proj_parte_categoria_sem_carga'), models.UniqueConstraint(condition=models.Q(('carga__isnull', False)), fields=('projeto', 'parte_painel', 'categoria_produto', 'carga', 'indice_escopo'), name='uq_composicao_item_proj_parte_categoria_carga_escopo')],
            },
        ),
        migrations.CreateModel(
            name='PendenciaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parte_painel', models.CharField(choices=[('SECCIONAMENTO', 'Seccionamento'), ('PROTECAO_GERAL', 'Proteção geral'), ('PROTECAO_CARGA', 'Proteção de carga'), ('ACIONAMENTO_CARGA', 'Acionamento de carga'), ('ENTRADA_PRINCIPAL', 'Entrada principal'), ('POTENCIA', 'Potência'), ('COMANDO', 'Comando'), ('BOTOEIRAS', 'Botoeiras'), ('AUTOMACAO', 'Automação'), ('BORNES', 'Bornes'), ('CANALETAS', 'Canaletas'), ('CLIMATIZACAO', 'Climatização'), ('ILUMINACAO', 'Iluminação'), ('TOMADA_SERVICO', 'Tomada de serviço'), ('ESTRUTURA', 'Estrutura'), ('IDENTIFICACAO', 'Identificação'), ('ACESSORIOS', 'Acessórios'), ('OUTROS', 'Outros')], max_length=50)),
                ('categoria_produto', models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada'), ('MINIDISJUNTOR', 'Minidisjuntor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('SECCIONADORA', 'Seccionadora'), ('FUSIVEL', 'Fusível'), ('RELE_ESTADO_SOLIDO', 'Relé Estado Sólido'), ('INVERSOR_FREQUENCIA', 'Inversor de Frequência'), ('SOFT_STARTER', 'Soft Starter'), ('BOTAO', 'Botão de Comando'), ('CHAVE_SELETORA', 'Chave Seletora'), ('SINALIZADOR', 'Sinaleiro'), ('RELE_INTERFACE', 'Relé de Interface'), ('TEMPORIZADOR', 'Relé Temporizador'), ('CONTROLADOR_TEMPERATURA', 'Controlador de Temperatura'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('IHM', 'Interface Homem Máquina (IHM)'), ('MODULO_COMUNICACAO', 'Módulo de Comunicação'), ('GATEWAY', 'Gateway'), ('SWITCH_REDE', 'Switch Industrial'), ('FONTE_CHAVEADA', 'Fonte Chaveada'), ('BORNE', 'Borne'), ('BARRAMENTO', 'Barramento'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('TRILHO_DIN', 'Trilho DIN'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros'), ('SEM_REGRA_SUGESTAO_AUTOMATICA', 'Sem regra de sugestão automática')], max_length=50)),
                ('corrente_referencia_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField()),
                ('memoria_calculo', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('RESOLVIDA', 'Resolvida'), ('IGNORADA', 'Ignorada')], default='ABERTA', max_length=30)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('indice_escopo', models.PositiveSmallIntegerField(default=0, help_text='Índice para múltiplas pendências do mesmo escopo (ex.: contatoras Y-Δ).')),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_itens', to='cargas.carga')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_itens', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Pendência de Item',
                'verbose_name_plural': 'Pendências de Itens',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto'), name='uq_pendencia_item_proj_parte_categoria_sem_carga'), models.UniqueConstraint(condition=models.Q(('carga__isnull', False)), fields=('projeto', 'parte_painel', 'categoria_produto', 'carga', 'indice_escopo'), name='uq_pendencia_item_proj_parte_categoria_carga_escopo')],
            },
        ),
        migrations.CreateModel(
            name='SugestaoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parte_painel', models.CharField(choices=[('SECCIONAMENTO', 'Seccionamento'), ('PROTECAO_GERAL', 'Proteção geral'), ('PROTECAO_CARGA', 'Proteção de carga'), ('ACIONAMENTO_CARGA', 'Acionamento de carga'), ('ENTRADA_PRINCIPAL', 'Entrada principal'), ('POTENCIA', 'Potência'), ('COMANDO', 'Comando'), ('BOTOEIRAS', 'Botoeiras'), ('AUTOMACAO', 'Automação'), ('BORNES', 'Bornes'), ('CANALETAS', 'Canaletas'), ('CLIMATIZACAO', 'Climatização'), ('ILUMINACAO', 'Iluminação'), ('TOMADA_SERVICO', 'Tomada de serviço'), ('ESTRUTURA', 'Estrutura'), ('IDENTIFICACAO', 'Identificação'), ('ACESSORIOS', 'Acessórios'), ('OUTROS', 'Outros')], max_length=50)),
                ('categoria_produto', models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada'), ('MINIDISJUNTOR', 'Minidisjuntor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('SECCIONADORA', 'Seccionadora'), ('FUSIVEL', 'Fusível'), ('RELE_ESTADO_SOLIDO', 'Relé Estado Sólido'), ('INVERSOR_FREQUENCIA', 'Inversor de Frequência'), ('SOFT_STARTER', 'Soft Starter'), ('BOTAO', 'Botão de Comando'), ('CHAVE_SELETORA', 'Chave Seletora'), ('SINALIZADOR', 'Sinaleiro'), ('RELE_INTERFACE', 'Relé de Interface'), ('TEMPORIZADOR', 'Relé Temporizador'), ('CONTROLADOR_TEMPERATURA', 'Controlador de Temperatura'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('IHM', 'Interface Homem Máquina (IHM)'), ('MODULO_COMUNICACAO', 'Módulo de Comunicação'), ('GATEWAY', 'Gateway'), ('SWITCH_REDE', 'Switch Industrial'), ('FONTE_CHAVEADA', 'Fonte Chaveada'), ('BORNE', 'Borne'), ('BARRAMENTO', 'Barramento'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('TRILHO_DIN', 'Trilho DIN'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros'), ('SEM_REGRA_SUGESTAO_AUTOMATICA', 'Sem regra de sugestão automática')], max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('corrente_referencia_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memoria_calculo', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('SUBSTITUIDA', 'Substituída')], default='PENDENTE', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('indice_escopo', models.PositiveSmallIntegerField(default=0, help_text='Diferencia várias sugestões da mesma categoria para a mesma carga (ex.: K1/K2/K3 em estrela-triângulo). Padrão 0.')),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_itens', to='cargas.carga')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_itens', to='catalogo.produto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_itens', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Sugestão de Item',
                'verbose_name_plural': 'Sugestões de Itens',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto'), name='uq_sugestao_item_proj_parte_categoria_sem_carga'), models.UniqueConstraint(condition=models.Q(('carga__isnull', False)), fields=('projeto', 'parte_painel', 'categoria_produto', 'carga', 'indice_escopo'), name='uq_sugestao_item_proj_parte_categoria_carga_escopo')],
            },
        ),
    ]
