# Generated by Django 5.2.1 on 2026-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0002_remove_null_from_optional_charfields'),
        ('catalogo', '0010_add_tipo_borne_poste'),
        ('composicao_painel', '0001_initial'),
        ('projetos', '0004_disjuntor_geral'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pendenciaitem',
            name='uq_pendencia_item_proj_parte_categoria_sem_carga',
        ),
        migrations.RemoveConstraint(
            model_name='sugestaoitem',
            name='uq_sugestao_item_proj_parte_categoria_sem_carga',
        ),
        migrations.AddConstraint(
            model_name='pendenciaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto', 'indice_escopo'), name='uq_pendencia_item_proj_parte_categoria_sem_carga'),
        ),
        migrations.AddConstraint(
            model_name='sugestaoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto', 'indice_escopo'), name='uq_sugestao_item_proj_parte_categoria_sem_carga'),
        ),
    ]
