# Generated by Django 5.2.1 on 2026-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicao_painel', '0002_allow_borne_accessory_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaoitem',
            name='categoria_produto',
            field=models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada'), ('MINIDISJUNTOR', 'Minidisjuntor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('SECCIONADORA', 'Seccionadora'), ('FUSIVEL', 'Fusível'), ('RELE_ESTADO_SOLIDO', 'Relé Estado Sólido'), ('INVERSOR_FREQUENCIA', 'Inversor de Frequência'), ('SOFT_STARTER', 'Soft Starter'), ('BOTAO', 'Botão de Comando'), ('CHAVE_SELETORA', 'Chave Seletora'), ('SINALIZADOR', 'Sinaleiro'), ('RELE_INTERFACE', 'Relé de Interface'), ('TEMPORIZADOR', 'Relé Temporizador'), ('CONTROLADOR_TEMPERATURA', 'Controlador de Temperatura'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('IHM', 'Interface Homem Máquina (IHM)'), ('MODULO_COMUNICACAO', 'Módulo de Comunicação'), ('GATEWAY', 'Gateway'), ('SWITCH_REDE', 'Switch Industrial'), ('RELE_SEGURANCA', 'Relé de Segurança'), ('FONTE_CHAVEADA', 'Fonte Chaveada'), ('BORNE', 'Borne'), ('BARRAMENTO', 'Barramento'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('TRILHO_DIN', 'Trilho DIN'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('IDENTIFICACAO', 'Identificação'), ('TERMINAIS', 'Terminais'), ('ACESSORIOS_GERAIS', 'Acessórios Gerais'), ('OUTROS', 'Outros'), ('SEM_REGRA_SUGESTAO_AUTOMATICA', 'Sem regra de sugestão automática')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendenciaitem',
            name='categoria_produto',
            field=models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada'), ('MINIDISJUNTOR', 'Minidisjuntor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('SECCIONADORA', 'Seccionadora'), ('FUSIVEL', 'Fusível'), ('RELE_ESTADO_SOLIDO', 'Relé Estado Sólido'), ('INVERSOR_FREQUENCIA', 'Inversor de Frequência'), ('SOFT_STARTER', 'Soft Starter'), ('BOTAO', 'Botão de Comando'), ('CHAVE_SELETORA', 'Chave Seletora'), ('SINALIZADOR', 'Sinaleiro'), ('RELE_INTERFACE', 'Relé de Interface'), ('TEMPORIZADOR', 'Relé Temporizador'), ('CONTROLADOR_TEMPERATURA', 'Controlador de Temperatura'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('IHM', 'Interface Homem Máquina (IHM)'), ('MODULO_COMUNICACAO', 'Módulo de Comunicação'), ('GATEWAY', 'Gateway'), ('SWITCH_REDE', 'Switch Industrial'), ('RELE_SEGURANCA', 'Relé de Segurança'), ('FONTE_CHAVEADA', 'Fonte Chaveada'), ('BORNE', 'Borne'), ('BARRAMENTO', 'Barramento'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('TRILHO_DIN', 'Trilho DIN'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('IDENTIFICACAO', 'Identificação'), ('TERMINAIS', 'Terminais'), ('ACESSORIOS_GERAIS', 'Acessórios Gerais'), ('OUTROS', 'Outros'), ('SEM_REGRA_SUGESTAO_AUTOMATICA', 'Sem regra de sugestão automática')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sugestaoitem',
            name='categoria_produto',
            field=models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada'), ('MINIDISJUNTOR', 'Minidisjuntor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('SECCIONADORA', 'Seccionadora'), ('FUSIVEL', 'Fusível'), ('RELE_ESTADO_SOLIDO', 'Relé Estado Sólido'), ('INVERSOR_FREQUENCIA', 'Inversor de Frequência'), ('SOFT_STARTER', 'Soft Starter'), ('BOTAO', 'Botão de Comando'), ('CHAVE_SELETORA', 'Chave Seletora'), ('SINALIZADOR', 'Sinaleiro'), ('RELE_INTERFACE', 'Relé de Interface'), ('TEMPORIZADOR', 'Relé Temporizador'), ('CONTROLADOR_TEMPERATURA', 'Controlador de Temperatura'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('IHM', 'Interface Homem Máquina (IHM)'), ('MODULO_COMUNICACAO', 'Módulo de Comunicação'), ('GATEWAY', 'Gateway'), ('SWITCH_REDE', 'Switch Industrial'), ('RELE_SEGURANCA', 'Relé de Segurança'), ('FONTE_CHAVEADA', 'Fonte Chaveada'), ('BORNE', 'Borne'), ('BARRAMENTO', 'Barramento'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('TRILHO_DIN', 'Trilho DIN'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('IDENTIFICACAO', 'Identificação'), ('TERMINAIS', 'Terminais'), ('ACESSORIOS_GERAIS', 'Acessórios Gerais'), ('OUTROS', 'Outros'), ('SEM_REGRA_SUGESTAO_AUTOMATICA', 'Sem regra de sugestão automática')], max_length=50),
        ),
    ]
