# Generated by Django 5.2.12 on 2026-03-20 01:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tag', models.CharField(help_text='Ex.: M01, YV01, R01, ST01', max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('MOTOR', 'Motor'), ('VALVULA', 'Válvula'), ('RESISTENCIA', 'Resistência'), ('SENSOR', 'Sensor'), ('TRANSDUTOR', 'Transdutor'), ('TRANSMISSOR', 'Transmissor'), ('OUTRO', 'Outro')], max_length=30)),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('local_instalacao', models.CharField(blank=True, help_text='Ex.: Campo, skid, painel, área externa', max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('exige_protecao', models.BooleanField(default=True)),
                ('exige_seccionamento', models.BooleanField(default=False)),
                ('exige_comando', models.BooleanField(default=False)),
                ('exige_fonte_auxiliar', models.BooleanField(default=False)),
                ('ocupa_entrada_digital', models.BooleanField(default=False)),
                ('ocupa_entrada_analogica', models.BooleanField(default=False)),
                ('ocupa_saida_digital', models.BooleanField(default=False)),
                ('ocupa_saida_analogica', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['projeto', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='CargaMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_corrente_valor', models.DecimalField(decimal_places=2, help_text='Valor informado em CV, kW ou A.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('potencia_corrente_unidade', models.CharField(choices=[('CV', 'CV'), ('KW', 'kW'), ('A', 'Ampere')], default='CV', help_text='Unidade do valor informado.', max_length=5)),
                ('rendimento_percentual', models.DecimalField(blank=True, decimal_places=2, default=Decimal('85.00'), help_text='Rendimento do motor em percentual. Ex.: 85.00', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fator_potencia', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.85'), help_text='Fator de potência em formato decimal. Ex.: 0.85', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo_partida', models.CharField(choices=[('DIRETA', 'Direta'), ('ESTRELA_TRIANGULO', 'Estrela-Triângulo'), ('SOFT_STARTER', 'Soft Starter'), ('INVERSOR', 'Inversor'), ('SERVO_DRIVE', 'Servo Drive')], default='DIRETA', max_length=30)),
                ('reversivel', models.BooleanField(default=False)),
                ('freio_motor', models.BooleanField(default=False)),
                ('tempo_partida_s', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('potencia_kw_calculada', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=10, null=True)),
                ('corrente_calculada_a', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'MOTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='motor', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Motor',
                'verbose_name_plural': 'Especificações de Motores',
            },
        ),
        migrations.CreateModel(
            name='CargaResistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controle_em_etapas', models.BooleanField(default=False)),
                ('quantidade_etapas', models.PositiveIntegerField(default=1)),
                ('controle_pid', models.BooleanField(default=False)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'RESISTENCIA'}, on_delete=django.db.models.deletion.CASCADE, related_name='resistencia', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Resistência',
                'verbose_name_plural': 'Especificações de Resistências',
            },
        ),
        migrations.CreateModel(
            name='CargaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sensor', models.CharField(choices=[('INDUTIVO', 'Indutivo'), ('CAPACITIVO', 'Capacitivo'), ('FOTOELETRICO', 'Fotoelétrico'), ('FIM_DE_CURSO', 'Fim de curso'), ('PRESSOSTATO', 'Pressostato'), ('TERMOSTATO', 'Termostato'), ('CHAVE_NIVEL', 'Chave de nível'), ('ENCODER', 'Encoder'), ('OUTRO', 'Outro')], max_length=30)),
                ('tipo_sinal', models.CharField(choices=[('DIGITAL', 'Digital'), ('ANALOGICO', 'Analógico'), ('PULSO', 'Pulso'), ('COMUNICACAO', 'Comunicação')], max_length=20)),
                ('tipo_sinal_analogico', models.CharField(blank=True, choices=[('TENSAO_0_10VCC', 'Tensão 0-10 VCC'), ('TENSAO_M10_10VCC', 'Tensão -10 a 10 VCC'), ('CORRENTE_0_20MA', 'Corrente 0-20 mA'), ('CORRENTE_4_20MA', 'Corrente 4-20 mA'), ('TEMPERATURA_PT100', 'Temperatura PT100'), ('TEMPERATURA_RTD', 'Temperatura RTD'), ('OUTROS', 'Outros')], max_length=30, null=True)),
                ('pnp', models.BooleanField(default=False)),
                ('npn', models.BooleanField(default=False)),
                ('normalmente_aberto', models.BooleanField(default=False)),
                ('normalmente_fechado', models.BooleanField(default=False)),
                ('range_medicao', models.CharField(blank=True, max_length=100)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'SENSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Sensor',
                'verbose_name_plural': 'Especificações de Sensores',
            },
        ),
        migrations.CreateModel(
            name='CargaTransdutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transdutor', models.CharField(choices=[('PRESSAO', 'Pressão'), ('TEMPERATURA', 'Temperatura'), ('NIVEL', 'Nível'), ('VAZAO', 'Vazão'), ('POSICAO', 'Posição'), ('CORRENTE', 'Corrente'), ('TENSAO', 'Tensão'), ('OUTRO', 'Outro')], max_length=30)),
                ('faixa_medicao', models.CharField(blank=True, help_text='Ex.: 0-10 bar, 0-100 °C, 0-5 m', max_length=100)),
                ('tipo_sinal_analogico', models.CharField(blank=True, choices=[('TENSAO_0_10VCC', 'Tensão 0-10 VCC'), ('TENSAO_M10_10VCC', 'Tensão -10 a 10 VCC'), ('CORRENTE_0_20MA', 'Corrente 0-20 mA'), ('CORRENTE_4_20MA', 'Corrente 4-20 mA'), ('TEMPERATURA_PT100', 'Temperatura PT100'), ('TEMPERATURA_RTD', 'Temperatura RTD'), ('OUTROS', 'Outros')], max_length=30, null=True)),
                ('precisao', models.CharField(blank=True, max_length=50)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'TRANSDUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='transdutor', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Transdutor',
                'verbose_name_plural': 'Especificações de Transdutores',
            },
        ),
        migrations.CreateModel(
            name='CargaValvula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_valvula', models.CharField(choices=[('SOLENOIDE', 'Solenóide'), ('PROPORCIONAL', 'Proporcional'), ('MOTORIZADA', 'Motorizada'), ('PNEUMATICA', 'Pneumática'), ('OUTRA', 'Outra')], default='SOLENOIDE', max_length=30)),
                ('quantidade_vias', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_posicoes', models.PositiveIntegerField(blank=True, null=True)),
                ('retorno_mola', models.BooleanField(default=False)),
                ('possui_feedback', models.BooleanField(default=False)),
                ('carga', models.OneToOneField(limit_choices_to={'tipo': 'VALVULA'}, on_delete=django.db.models.deletion.CASCADE, related_name='valvula', to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Especificação de Válvula',
                'verbose_name_plural': 'Especificações de Válvulas',
            },
        ),
        migrations.AddConstraint(
            model_name='carga',
            constraint=models.UniqueConstraint(fields=('projeto', 'tag'), name='unique_tag_por_projeto'),
        ),
    ]
