# Generated by Django 5.2.12 on 2026-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamotor',
            name='tipo_protecao',
            field=models.CharField(choices=[('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('FUSIVEL', 'Fusível'), ('MINI_DISJUNTOR', 'Mini Disjuntor'), ('OUTRO', 'Outro')], default='DISJUNTOR_MOTOR', help_text='Tipo de proteção elétrica do motor.', max_length=30),
        ),
    ]
