# Generated by Django 5.2.12 on 2026-03-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0002_cargamotor_tipo_protecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamotor',
            name='tipo_conexao_painel',
            field=models.CharField(choices=[('CONEXAO_BORNES_COM_PE', 'Conexão a bornes com PE'), ('CONEXAO_BORNES_SEM_PE', 'Conexão a bornes sem PE'), ('CONEXAO_DIRETO_COMPONENTE', 'Conexão direta ao componente'), ('OUTROS', 'Outros')], default='CONEXAO_BORNES_COM_PE', help_text='Define como a carga será conectada ao painel elétrico.', max_length=50),
        ),
    ]
