"""Rotas da API de composição do painel."""

from django.urls import path

from apps.configurador_paineis.composicao_painel.api.views import (
    ComposicaoExportPdfView,
    ComposicaoExportXlsxView,
    ComposicaoGerarSugestoesView,
    ComposicaoInclusaoManualCreateView,
    ComposicaoInclusaoManualDestroyView,
    ComposicaoItemReabrirView,
    ComposicaoProjetoSnapshotView,
    ComposicaoReavaliarPendenciasView,
    SugestaoAlternativasView,
    SugestaoAprovarView,
)

urlpatterns = [
    path(
        "composicao/projeto/<uuid:projeto_id>/",
        ComposicaoProjetoSnapshotView.as_view(),
        name="composicao-projeto-snapshot",
    ),
    path(
        "configurador/composicao/projeto/<uuid:projeto_id>/",
        ComposicaoProjetoSnapshotView.as_view(),
        name="configurador-composicao-projeto-snapshot",
    ),
    path(
        "composicao/projeto/<uuid:projeto_id>/gerar-sugestoes/",
        ComposicaoGerarSugestoesView.as_view(),
        name="composicao-projeto-gerar-sugestoes",
    ),
    path(
        "configurador/composicao/projeto/<uuid:projeto_id>/gerar-sugestoes/",
        ComposicaoGerarSugestoesView.as_view(),
        name="configurador-composicao-projeto-gerar-sugestoes",
    ),
    path(
        "composicao/projeto/<uuid:projeto_id>/reavaliar-pendencias/",
        ComposicaoReavaliarPendenciasView.as_view(),
        name="composicao-projeto-reavaliar-pendencias",
    ),
    path(
        "configurador/composicao/projeto/<uuid:projeto_id>/reavaliar-pendencias/",
        ComposicaoReavaliarPendenciasView.as_view(),
        name="configurador-composicao-projeto-reavaliar-pendencias",
    ),
    path(
        "composicao/projeto/<uuid:projeto_id>/export/xlsx/",
        ComposicaoExportXlsxView.as_view(),
        name="composicao-projeto-export-xlsx",
    ),
    path(
        "configurador/composicao/projeto/<uuid:projeto_id>/export/xlsx/",
        ComposicaoExportXlsxView.as_view(),
        name="configurador-composicao-projeto-export-xlsx",
    ),
    path(
        "composicao/projeto/<uuid:projeto_id>/export/pdf/",
        ComposicaoExportPdfView.as_view(),
        name="composicao-projeto-export-pdf",
    ),
    path(
        "configurador/composicao/projeto/<uuid:projeto_id>/export/pdf/",
        ComposicaoExportPdfView.as_view(),
        name="configurador-composicao-projeto-export-pdf",
    ),
    path(
        "composicao/sugestoes/<uuid:sugestao_id>/alternativas/",
        SugestaoAlternativasView.as_view(),
        name="composicao-sugestao-alternativas",
    ),
    path(
        "configurador/composicao/sugestoes/<uuid:sugestao_id>/alternativas/",
        SugestaoAlternativasView.as_view(),
        name="configurador-composicao-sugestao-alternativas",
    ),
    path(
        "composicao/sugestoes/<uuid:sugestao_id>/aprovar/",
        SugestaoAprovarView.as_view(),
        name="composicao-sugestao-aprovar",
    ),
    path(
        "configurador/composicao/sugestoes/<uuid:sugestao_id>/aprovar/",
        SugestaoAprovarView.as_view(),
        name="configurador-composicao-sugestao-aprovar",
    ),
    path(
        "composicao/projeto/<uuid:projeto_id>/inclusoes-manuais/",
        ComposicaoInclusaoManualCreateView.as_view(),
        name="composicao-projeto-inclusoes-manuais",
    ),
    path(
        "configurador/composicao/projeto/<uuid:projeto_id>/inclusoes-manuais/",
        ComposicaoInclusaoManualCreateView.as_view(),
        name="configurador-composicao-projeto-inclusoes-manuais",
    ),
    path(
        "composicao/inclusoes-manuais/<uuid:inclusao_id>/",
        ComposicaoInclusaoManualDestroyView.as_view(),
        name="composicao-inclusao-manual-detail",
    ),
    path(
        "configurador/composicao/inclusoes-manuais/<uuid:inclusao_id>/",
        ComposicaoInclusaoManualDestroyView.as_view(),
        name="configurador-composicao-inclusao-manual-detail",
    ),
    path(
        "composicao/itens/<uuid:composicao_item_id>/reabrir/",
        ComposicaoItemReabrirView.as_view(),
        name="composicao-item-reabrir",
    ),
    path(
        "configurador/composicao/itens/<uuid:composicao_item_id>/reabrir/",
        ComposicaoItemReabrirView.as_view(),
        name="configurador-composicao-item-reabrir",
    ),
]
