# Generated by Django 5.2.12 on 2026-03-22 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('projetos', '0008_alter_projeto_tensao_comando_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parte_painel', models.CharField(choices=[('SECCIONAMENTO', 'Seccionamento'), ('PROTECAO_GERAL', 'Proteção geral'), ('PROTECAO_CARGA', 'Proteção de carga'), ('ACIONAMENTO_CARGA', 'Acionamento de carga'), ('ENTRADA_PRINCIPAL', 'Entrada principal'), ('POTENCIA', 'Potência'), ('COMANDO', 'Comando'), ('BOTOEIRAS', 'Botoeiras'), ('AUTOMACAO', 'Automação'), ('BORNES', 'Bornes'), ('CANALETAS', 'Canaletas'), ('CLIMATIZACAO', 'Climatização'), ('ILUMINACAO', 'Iluminação'), ('TOMADA_SERVICO', 'Tomada de serviço'), ('ESTRUTURA', 'Estrutura'), ('IDENTIFICACAO', 'Identificação'), ('ACESSORIOS', 'Acessórios'), ('OUTROS', 'Outros')], max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('corrente_referencia_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memoria_calculo', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('SUBSTITUIDA', 'Substituída')], default='PENDENTE', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_itens', to='catalogo.produto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_itens', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Sugestão de Item',
                'verbose_name_plural': 'Sugestões de Itens',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'parte_painel'), name='uq_sugestao_item_projeto_parte')],
            },
        ),
    ]
