# Generated by Django 5.2.12 on 2026-03-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_cargamotor_tipo_conexao_painel'),
        ('composicao_painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestaoitem',
            name='carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_itens', to='cargas.carga'),
        ),
    ]
