# Generated by Django 5.2.12 on 2026-03-22 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_cargamotor_tipo_conexao_painel'),
        ('composicao_painel', '0003_alter_sugestaoitem_constraints'),
        ('projetos', '0009_alter_projeto_tensao_nominal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parte_painel', models.CharField(choices=[('SECCIONAMENTO', 'Seccionamento'), ('PROTECAO_GERAL', 'Proteção geral'), ('PROTECAO_CARGA', 'Proteção de carga'), ('ACIONAMENTO_CARGA', 'Acionamento de carga'), ('ENTRADA_PRINCIPAL', 'Entrada principal'), ('POTENCIA', 'Potência'), ('COMANDO', 'Comando'), ('BOTOEIRAS', 'Botoeiras'), ('AUTOMACAO', 'Automação'), ('BORNES', 'Bornes'), ('CANALETAS', 'Canaletas'), ('CLIMATIZACAO', 'Climatização'), ('ILUMINACAO', 'Iluminação'), ('TOMADA_SERVICO', 'Tomada de serviço'), ('ESTRUTURA', 'Estrutura'), ('IDENTIFICACAO', 'Identificação'), ('ACESSORIOS', 'Acessórios'), ('OUTROS', 'Outros')], max_length=50)),
                ('corrente_referencia_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField()),
                ('memoria_calculo', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('RESOLVIDA', 'Resolvida'), ('IGNORADA', 'Ignorada')], default='ABERTA', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_itens', to='cargas.carga')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_itens', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Pendência de Item',
                'verbose_name_plural': 'Pendências de Itens',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel'), name='uq_pendencia_item_projeto_parte_sem_carga'), models.UniqueConstraint(condition=models.Q(('carga__isnull', False)), fields=('projeto', 'parte_painel', 'carga'), name='uq_pendencia_item_projeto_parte_carga')],
            },
        ),
    ]
