# Generated by Django 5.2.12 on 2026-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_cargamotor_tipo_conexao_painel'),
        ('catalogo', '0001_initial'),
        ('composicao_painel', '0004_pendenciaitem'),
        ('projetos', '0009_alter_projeto_tensao_nominal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pendenciaitem',
            name='uq_pendencia_item_projeto_parte_sem_carga',
        ),
        migrations.RemoveConstraint(
            model_name='pendenciaitem',
            name='uq_pendencia_item_projeto_parte_carga',
        ),
        migrations.RemoveConstraint(
            model_name='sugestaoitem',
            name='uq_sugestao_item_projeto_parte_sem_carga',
        ),
        migrations.RemoveConstraint(
            model_name='sugestaoitem',
            name='uq_sugestao_item_projeto_parte_carga',
        ),
        migrations.AddField(
            model_name='pendenciaitem',
            name='categoria_produto',
            field=models.CharField(blank=True, choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('MINI_DISJUNTOR', 'Mini disjuntor'), ('SECCIONADORA', 'Seccionadora'), ('FONTE', 'Fonte'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('BORNE', 'Borne'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sugestaoitem',
            name='categoria_produto',
            field=models.CharField(blank=True, choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('MINI_DISJUNTOR', 'Mini disjuntor'), ('SECCIONADORA', 'Seccionadora'), ('FONTE', 'Fonte'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('BORNE', 'Borne'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendenciaitem',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('RESOLVIDA', 'Resolvida'), ('IGNORADA', 'Ignorada')], default='ABERTA', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='pendenciaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto'), name='uq_pendencia_item_proj_parte_categoria_sem_carga'),
        ),
        migrations.AddConstraint(
            model_name='pendenciaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('carga__isnull', False)), fields=('projeto', 'parte_painel', 'categoria_produto', 'carga'), name='uq_pendencia_item_proj_parte_categoria_carga'),
        ),
        migrations.AddConstraint(
            model_name='sugestaoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto'), name='uq_sugestao_item_proj_parte_categoria_sem_carga'),
        ),
        migrations.AddConstraint(
            model_name='sugestaoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('carga__isnull', False)), fields=('projeto', 'parte_painel', 'categoria_produto', 'carga'), name='uq_sugestao_item_proj_parte_categoria_carga'),
        ),
    ]
