# Generated by Django 5.2.12 on 2026-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicao_painel', '0005_remove_pendenciaitem_uq_pendencia_item_projeto_parte_sem_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciaitem',
            name='categoria_produto',
            field=models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('MINI_DISJUNTOR', 'Mini disjuntor'), ('SECCIONADORA', 'Seccionadora'), ('FONTE', 'Fonte'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('BORNE', 'Borne'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sugestaoitem',
            name='categoria_produto',
            field=models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('MINI_DISJUNTOR', 'Mini disjuntor'), ('SECCIONADORA', 'Seccionadora'), ('FONTE', 'Fonte'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('BORNE', 'Borne'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros')], max_length=50),
        ),
    ]
