# Generated by Django 5.2.12 on 2026-03-26 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_cargamotor_tipo_conexao_painel'),
        ('catalogo', '0001_initial'),
        ('composicao_painel', '0006_alter_pendenciaitem_categoria_produto_and_more'),
        ('projetos', '0009_alter_projeto_tensao_nominal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parte_painel', models.CharField(choices=[('SECCIONAMENTO', 'Seccionamento'), ('PROTECAO_GERAL', 'Proteção geral'), ('PROTECAO_CARGA', 'Proteção de carga'), ('ACIONAMENTO_CARGA', 'Acionamento de carga'), ('ENTRADA_PRINCIPAL', 'Entrada principal'), ('POTENCIA', 'Potência'), ('COMANDO', 'Comando'), ('BOTOEIRAS', 'Botoeiras'), ('AUTOMACAO', 'Automação'), ('BORNES', 'Bornes'), ('CANALETAS', 'Canaletas'), ('CLIMATIZACAO', 'Climatização'), ('ILUMINACAO', 'Iluminação'), ('TOMADA_SERVICO', 'Tomada de serviço'), ('ESTRUTURA', 'Estrutura'), ('IDENTIFICACAO', 'Identificação'), ('ACESSORIOS', 'Acessórios'), ('OUTROS', 'Outros')], max_length=50)),
                ('categoria_produto', models.CharField(choices=[('CONTATORA', 'Contatora'), ('DISJUNTOR_MOTOR', 'Disjuntor Motor'), ('RELE_SOBRECARGA', 'Relé de Sobrecarga'), ('MINI_DISJUNTOR', 'Mini disjuntor'), ('SECCIONADORA', 'Seccionadora'), ('FONTE', 'Fonte'), ('PLC', 'PLC'), ('EXPANSAO_PLC', 'Expansão PLC'), ('BORNE', 'Borne'), ('CABO', 'Cabo'), ('CANALETA', 'Canaleta'), ('PAINEL', 'Painel'), ('CLIMATIZACAO', 'Climatização'), ('OUTROS', 'Outros')], max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('corrente_referencia_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memoria_calculo', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composicao_itens', to='cargas.carga')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_itens', to='catalogo.produto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_itens', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Item da Composição',
                'verbose_name_plural': 'Itens da Composição',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('carga__isnull', True)), fields=('projeto', 'parte_painel', 'categoria_produto'), name='uq_composicao_item_proj_parte_categoria_sem_carga'), models.UniqueConstraint(condition=models.Q(('carga__isnull', False)), fields=('projeto', 'parte_painel', 'categoria_produto', 'carga'), name='uq_composicao_item_proj_parte_categoria_carga')],
            },
        ),
    ]
