# Generated by Django 5.2

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
        ("composicao_painel", "0007_composicaoitem"),
        ("projetos", "0009_alter_projeto_tensao_nominal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposicaoInclusaoManual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inclusoes_manuais_composicao",
                        to="catalogo.produto",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicao_inclusoes_manuais",
                        to="projetos.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inclusão manual (catálogo)",
                "verbose_name_plural": "Inclusões manuais (catálogo)",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
