# Generated by Django 5.2.12 on 2026-03-20 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(help_text='Código interno do projeto. Ex.: PRJ-0001', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Nome resumido do projeto.', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do projeto.')),
                ('cliente', models.CharField(blank=True, help_text='Nome do cliente, provisoriamente em texto.', max_length=255)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['codigo', 'nome'],
            },
        ),
    ]
