# Generated by Django 5.2.12 on 2026-03-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='frequencia',
            field=models.IntegerField(blank=True, choices=[(50, '50 Hz'), (60, '60 Hz')], default=60, help_text='Frequência da alimentação principal.', null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='numero_fases',
            field=models.IntegerField(blank=True, choices=[(1, 'Monofásico'), (2, 'Bifásico'), (3, 'Trifásico')], help_text='Número de fases da alimentação principal.', null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tensao_nominal',
            field=models.IntegerField(blank=True, choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], help_text='Tensão principal do projeto/painel.', null=True),
        ),
    ]
