# Generated by Django 5.2.12 on 2026-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_frequencia_projeto_numero_fases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='fator_demanda',
            field=models.DecimalField(decimal_places=2, default='1.00', help_text='Ex.: 0.70 para 70%.', max_digits=4),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_neutro',
            field=models.BooleanField(default=True, help_text='Indica se a alimentação principal possui neutro.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_seccionamento',
            field=models.BooleanField(default=True, help_text='Indica se o projeto possui seccionamento geral.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_terra',
            field=models.BooleanField(default=True, help_text='Indica se a alimentação principal possui PE/terra.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', help_text='Status atual do projeto.', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tensao_comando',
            field=models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=24, help_text='Tensão de alimentação do comando.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_corrente',
            field=models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CA', help_text='Tipo de corrente da alimentação principal.', max_length=2),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_corrente_comando',
            field=models.CharField(choices=[('CA', 'Corrente Alternada'), ('CC', 'Corrente Contínua')], default='CC', help_text='Tipo de corrente da alimentação de comando.', max_length=2),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_painel',
            field=models.CharField(choices=[('AUTOMACAO', 'Automação'), ('DISTRIBUICAO', 'Distribuição')], default='AUTOMACAO', help_text='Tipo de painel do projeto.', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_seccionamento',
            field=models.CharField(blank=True, choices=[('NENHUM', 'Sem seccionamento'), ('SECCIONADORA', 'Seccionadora'), ('DISJUNTOR_CAIXA_MOLDADA', 'Disjuntor Caixa Moldada')], default='SECCIONADORA', help_text='Tipo de seccionamento geral.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='frequencia',
            field=models.IntegerField(blank=True, choices=[(50, '50 Hz'), (60, '60 Hz')], default=60, help_text='Frequência da alimentação principal. Aplicável para CA.', null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='numero_fases',
            field=models.IntegerField(blank=True, choices=[(1, 'Monofásico'), (2, 'Bifásico'), (3, 'Trifásico')], help_text='Número de fases da alimentação principal. Aplicável para CA.', null=True),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['codigo'], name='projetos_pr_codigo_89df55_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tipo_painel', 'status'], name='projetos_pr_tipo_pa_add7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tipo_corrente'], name='projetos_pr_tipo_co_3f0aca_idx'),
        ),
    ]
