# Generated by Django 5.2.12 on 2026-03-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_projeto_fator_demanda_projeto_possui_neutro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo_conexao_alimentacao_neutro',
            field=models.CharField(choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], default='BORNE', help_text='Tipo de conexão do neutro da alimentação.', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_conexao_alimentacao_potencia',
            field=models.CharField(choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], default='BORNE', help_text='Tipo de conexão da alimentação de potência.', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_conexao_alimentacao_terra',
            field=models.CharField(choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], default='BORNE', help_text='Tipo de conexão do terra da alimentação.', max_length=20),
        ),
    ]
