# Generated by Django 5.2.12 on 2026-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_projeto_tipo_conexao_alimentacao_neutro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tipo_conexao_alimentacao_neutro',
            field=models.CharField(blank=True, choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], help_text='Tipo de conexão do neutro da alimentação.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_conexao_alimentacao_terra',
            field=models.CharField(blank=True, choices=[('BARRAMENTO', 'Barramento'), ('BORNE', 'Borne'), ('TOMADA', 'Tomada'), ('DIRETO', 'Direto'), ('OUTRO', 'Outro')], help_text='Tipo de conexão do terra da alimentação.', max_length=20, null=True),
        ),
    ]
