# Generated by Django 5.2.12 on 2026-03-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_projeto_tipo_conexao_alimentacao_neutro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='possui_climatizacao',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui climatização.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_plc',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui PLC.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_climatizacao',
            field=models.CharField(blank=True, choices=[('VENTILADOR', 'Ventilador'), ('EXAUSTOR', 'Exaustor'), ('AR_CONDICIONADO', 'Ar Condicionado'), ('OUTRO', 'Outro')], help_text='Tipo de climatização do painel, caso possua.', max_length=20, null=True),
        ),
    ]
