# Generated by Django 5.2.12 on 2026-03-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_projeto_possui_climatizacao_projeto_possui_plc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='possui_adesivo_alerta',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui adesivo de alerta de risco elétrico.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_adesivos_tensao',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui adesivos de indicação de tensão.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_faixa_identificacao',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui faixa de identificação da empresa na porta.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_ihm',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui IHM.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_plaqueta_identificacao',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui plaqueta de identificação da empresa.'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possui_switches',
            field=models.BooleanField(default=False, help_text='Indica se o projeto possui switch'),
        ),
    ]
