# Generated by Django 5.2.12 on 2026-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_alter_projeto_tensao_comando_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tensao_nominal',
            field=models.IntegerField(choices=[(12, '12 V'), (24, '24 V'), (48, '48 V'), (90, '90 V'), (110, '110 V'), (127, '127 V'), (220, '220 V'), (380, '380 V'), (440, '440 V')], default=380, help_text='Tensão principal do projeto/painel.'),
        ),
    ]
