# Generated by Django 5.2.12 on 2026-03-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_alter_projeto_tensao_nominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='EM_ANDAMENTO', help_text='Status atual do projeto.', max_length=20),
        ),
    ]
