# Generated by Django 5.2.1 on 2026-05-09 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=32, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('cliente_referencia', models.CharField(blank=True, help_text='Texto livre até existir cadastro de clientes.', max_length=200)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=20)),
                ('valido_ate', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'erp_orcamento',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('descricao', models.CharField(max_length=500)),
                ('quantidade', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('preco_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
            ],
            options={
                'db_table': 'erp_orcamento_item',
                'ordering': ('orcamento_id', 'ordem', 'id'),
            },
        ),
    ]
